// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectAPIKeys = `-- name: CountProjectAPIKeys :one
SELECT COUNT(*)
FROM api_keys
WHERE project_id = $1 AND is_active = true
`

// Count active API keys for a project
func (q *Queries) CountProjectAPIKeys(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectAPIKeys, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
  project_id,
  user_id,
  name,
  prefix,
  description,
  hashed_secret,
  scopes,
  is_active,
  expired_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
`

type CreateAPIKeyParams struct {
	ProjectID    uuid.UUID          `json:"project_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         pgtype.Text        `json:"name"`
	Prefix       pgtype.Text        `json:"prefix"`
	Description  pgtype.Text        `json:"description"`
	HashedSecret string             `json:"hashed_secret"`
	Scopes       []string           `json:"scopes"`
	IsActive     pgtype.Bool        `json:"is_active"`
	ExpiredAt    pgtype.Timestamptz `json:"expired_at"`
}

// API Key Management Queries
// Create a new API key for a project
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ProjectID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.Description,
		arg.HashedSecret,
		arg.Scopes,
		arg.IsActive,
		arg.ExpiredAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE key_id = $1
`

// Hard delete an API key (use with caution)
func (q *Queries) DeleteAPIKey(ctx context.Context, keyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, keyID)
	return err
}

const getAPIKeyByHashedSecret = `-- name: GetAPIKeyByHashedSecret :one
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE hashed_secret = $1
`

// Retrieve API key by its hashed secret (for validation)
func (q *Queries) GetAPIKeyByHashedSecret(ctx context.Context, hashedSecret string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHashedSecret, hashedSecret)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE key_id = $1
`

// Retrieve API key by ID
func (q *Queries) GetAPIKeyByID(ctx context.Context, keyID uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, keyID)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE prefix = $1
`

// Retrieve API key by prefix
func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix pgtype.Text) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAPIKeyByHashedSecret = `-- name: GetActiveAPIKeyByHashedSecret :one
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE hashed_secret = $1 AND is_active = true
`

// Get active API key by hashed secret (commonly used for validation)
func (q *Queries) GetActiveAPIKeyByHashedSecret(ctx context.Context, hashedSecret string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHashedSecret, hashedSecret)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByProject = `-- name: ListAPIKeysByProject :many
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE project_id = $1
ORDER BY key_id DESC
`

// List all API keys for a project (including revoked)
func (q *Queries) ListAPIKeysByProject(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.KeyID,
			&i.ProjectID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Description,
			&i.HashedSecret,
			&i.Scopes,
			&i.IsActive,
			&i.RevokedAt,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPIKeysByProject = `-- name: ListActiveAPIKeysByProject :many
SELECT key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
FROM api_keys
WHERE project_id = $1 AND is_active = true
ORDER BY key_id DESC
`

// List active API keys for a project
func (q *Queries) ListActiveAPIKeysByProject(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeysByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.KeyID,
			&i.ProjectID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.Description,
			&i.HashedSecret,
			&i.Scopes,
			&i.IsActive,
			&i.RevokedAt,
			&i.ExpiredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET is_active = false,
    revoked_at = CURRENT_TIMESTAMP
WHERE key_id = $1
RETURNING key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
`

// Revoke an API key (soft delete)
func (q *Queries) RevokeAPIKey(ctx context.Context, keyID uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, keyID)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateAPIKeyScopes = `-- name: UpdateAPIKeyScopes :one
UPDATE api_keys
SET scopes = $2
WHERE key_id = $1
RETURNING key_id, project_id, user_id, name, prefix, description, hashed_secret, scopes, is_active, revoked_at, expired_at, created_at
`

type UpdateAPIKeyScopesParams struct {
	KeyID  uuid.UUID `json:"key_id"`
	Scopes []string  `json:"scopes"`
}

// Update the scopes of an API key
func (q *Queries) UpdateAPIKeyScopes(ctx context.Context, arg UpdateAPIKeyScopesParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyScopes, arg.KeyID, arg.Scopes)
	var i ApiKey
	err := row.Scan(
		&i.KeyID,
		&i.ProjectID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.Description,
		&i.HashedSecret,
		&i.Scopes,
		&i.IsActive,
		&i.RevokedAt,
		&i.ExpiredAt,
		&i.CreatedAt,
	)
	return i, err
}
