// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: code_scans.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countScanDependencyResults = `-- name: CountScanDependencyResults :one
SELECT COUNT(*) FROM scan_dependency_results
WHERE scan_id = $1
  AND ($2::text = '' OR tool = $2)
  AND ($3::text = '' OR cve_severity = $3)
  AND ($4::text[] IS NULL OR cardinality($4::text[]) = 0 OR ecosystem = ANY($4::text[]))
  AND ($5::text[] IS NULL OR cardinality($5::text[]) = 0 OR language = ANY($5::text[]))
  AND (NOT $6::boolean OR is_outdated)
  AND (NOT $7::boolean OR is_vulnerable)
`

type CountScanDependencyResultsParams struct {
	ScanID  uuid.UUID `json:"scan_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 []string  `json:"column_4"`
	Column5 []string  `json:"column_5"`
	Column6 bool      `json:"column_6"`
	Column7 bool      `json:"column_7"`
}

func (q *Queries) CountScanDependencyResults(ctx context.Context, arg CountScanDependencyResultsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScanDependencyResults,
		arg.ScanID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnifiedProjectScans = `-- name: CountUnifiedProjectScans :one
SELECT COUNT(*) FROM scans
WHERE project_key = $1
`

func (q *Queries) CountUnifiedProjectScans(ctx context.Context, projectKey string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnifiedProjectScans, projectKey)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnifiedUserScans = `-- name: CountUnifiedUserScans :one
SELECT COUNT(*) FROM scans
WHERE user_id = $1
  AND ($2::text = '' OR project_key = $2)
`

type CountUnifiedUserScansParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
}

func (q *Queries) CountUnifiedUserScans(ctx context.Context, arg CountUnifiedUserScansParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnifiedUserScans, arg.UserID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRepositorySnapshot = `-- name: CreateRepositorySnapshot :one
INSERT INTO repository_snapshots (
    repository_id, branch_name, commit_sha,
    source_snapshot_hash, dependency_hash
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at
`

type CreateRepositorySnapshotParams struct {
	RepositoryID       uuid.UUID   `json:"repository_id"`
	BranchName         string      `json:"branch_name"`
	CommitSha          string      `json:"commit_sha"`
	SourceSnapshotHash string      `json:"source_snapshot_hash"`
	DependencyHash     pgtype.Text `json:"dependency_hash"`
}

func (q *Queries) CreateRepositorySnapshot(ctx context.Context, arg CreateRepositorySnapshotParams) (RepositorySnapshot, error) {
	row := q.db.QueryRow(ctx, createRepositorySnapshot,
		arg.RepositoryID,
		arg.BranchName,
		arg.CommitSha,
		arg.SourceSnapshotHash,
		arg.DependencyHash,
	)
	var i RepositorySnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.BranchName,
		&i.CommitSha,
		&i.SourceSnapshotHash,
		&i.DependencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const createUnifiedScan = `-- name: CreateUnifiedScan :one
INSERT INTO scans (
    project_key,
    repository_url,
    source_dir,
    branch,
    user_id,
    status,
    progress
)
VALUES ($1, $2, $3, $4, $5, 'PENDING', 0)
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type CreateUnifiedScanParams struct {
	ProjectKey    string      `json:"project_key"`
	RepositoryUrl pgtype.Text `json:"repository_url"`
	SourceDir     string      `json:"source_dir"`
	Branch        pgtype.Text `json:"branch"`
	UserID        uuid.UUID   `json:"user_id"`
}

func (q *Queries) CreateUnifiedScan(ctx context.Context, arg CreateUnifiedScanParams) (Scan, error) {
	row := q.db.QueryRow(ctx, createUnifiedScan,
		arg.ProjectKey,
		arg.RepositoryUrl,
		arg.SourceDir,
		arg.Branch,
		arg.UserID,
	)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const deleteUnifiedScan = `-- name: DeleteUnifiedScan :execrows
DELETE FROM scans
WHERE id = $1
`

func (q *Queries) DeleteUnifiedScan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnifiedScan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScanDependencyResultsByScan = `-- name: DeleteScanDependencyResultsByScan :exec
DELETE FROM scan_dependency_results
WHERE scan_id = $1
`

func (q *Queries) DeleteScanDependencyResultsByScan(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanDependencyResultsByScan, scanID)
	return err
}

const deleteScanPhasesByScan = `-- name: DeleteScanPhasesByScan :exec
DELETE FROM scan_phases
WHERE scan_id = $1
`

func (q *Queries) DeleteScanPhasesByScan(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanPhasesByScan, scanID)
	return err
}

const deleteScanSonarResultsByScan = `-- name: DeleteScanSonarResultsByScan :exec
DELETE FROM scan_sonar_results
WHERE scan_id = $1
`

func (q *Queries) DeleteScanSonarResultsByScan(ctx context.Context, scanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanSonarResultsByScan, scanID)
	return err
}

const getRepositorySnapshotByCommit = `-- name: GetRepositorySnapshotByCommit :one
SELECT id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at FROM repository_snapshots
WHERE repository_id = $1 AND commit_sha = $2
`

type GetRepositorySnapshotByCommitParams struct {
	RepositoryID uuid.UUID `json:"repository_id"`
	CommitSha    string    `json:"commit_sha"`
}

func (q *Queries) GetRepositorySnapshotByCommit(ctx context.Context, arg GetRepositorySnapshotByCommitParams) (RepositorySnapshot, error) {
	row := q.db.QueryRow(ctx, getRepositorySnapshotByCommit, arg.RepositoryID, arg.CommitSha)
	var i RepositorySnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.BranchName,
		&i.CommitSha,
		&i.SourceSnapshotHash,
		&i.DependencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositorySnapshotByID = `-- name: GetRepositorySnapshotByID :one
SELECT id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at FROM repository_snapshots
WHERE id = $1
`

func (q *Queries) GetRepositorySnapshotByID(ctx context.Context, id uuid.UUID) (RepositorySnapshot, error) {
	row := q.db.QueryRow(ctx, getRepositorySnapshotByID, id)
	var i RepositorySnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.BranchName,
		&i.CommitSha,
		&i.SourceSnapshotHash,
		&i.DependencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getRepositorySnapshotBySourceHash = `-- name: GetRepositorySnapshotBySourceHash :one
SELECT id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at FROM repository_snapshots
WHERE source_snapshot_hash = $1
`

func (q *Queries) GetRepositorySnapshotBySourceHash(ctx context.Context, sourceSnapshotHash string) (RepositorySnapshot, error) {
	row := q.db.QueryRow(ctx, getRepositorySnapshotBySourceHash, sourceSnapshotHash)
	var i RepositorySnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.BranchName,
		&i.CommitSha,
		&i.SourceSnapshotHash,
		&i.DependencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getScanDependencySummary = `-- name: GetScanDependencySummary :one
SELECT
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE is_vulnerable)::int AS vulnerable,
    COUNT(*) FILTER (WHERE is_outdated)::int AS outdated,
    COUNT(*) FILTER (WHERE has_license_issue)::int AS license_issues,
    COUNT(*) FILTER (WHERE cve_severity = 'CRITICAL')::int AS critical,
    COUNT(*) FILTER (WHERE cve_severity = 'HIGH')::int AS high,
    COUNT(*) FILTER (WHERE cve_severity = 'MEDIUM')::int AS medium,
    COUNT(*) FILTER (WHERE cve_severity = 'LOW')::int AS low
FROM scan_dependency_results
WHERE scan_id = $1
`

type GetScanDependencySummaryRow struct {
	Total         int32 `json:"total"`
	Vulnerable    int32 `json:"vulnerable"`
	Outdated      int32 `json:"outdated"`
	LicenseIssues int32 `json:"license_issues"`
	Critical      int32 `json:"critical"`
	High          int32 `json:"high"`
	Medium        int32 `json:"medium"`
	Low           int32 `json:"low"`
}

func (q *Queries) GetScanDependencySummary(ctx context.Context, scanID uuid.UUID) (GetScanDependencySummaryRow, error) {
	row := q.db.QueryRow(ctx, getScanDependencySummary, scanID)
	var i GetScanDependencySummaryRow
	err := row.Scan(
		&i.Total,
		&i.Vulnerable,
		&i.Outdated,
		&i.LicenseIssues,
		&i.Critical,
		&i.High,
		&i.Medium,
		&i.Low,
	)
	return i, err
}

const getScanDependencySummaryByEcosystem = `-- name: GetScanDependencySummaryByEcosystem :many
SELECT COALESCE(ecosystem, 'OTHER') AS ecosystem, COUNT(*)::int AS total
FROM scan_dependency_results
WHERE scan_id = $1
GROUP BY COALESCE(ecosystem, 'OTHER')
ORDER BY total DESC, ecosystem ASC
`

type GetScanDependencySummaryByEcosystemRow struct {
	Ecosystem string `json:"ecosystem"`
	Total     int32  `json:"total"`
}

func (q *Queries) GetScanDependencySummaryByEcosystem(ctx context.Context, scanID uuid.UUID) ([]GetScanDependencySummaryByEcosystemRow, error) {
	rows, err := q.db.Query(ctx, getScanDependencySummaryByEcosystem, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScanDependencySummaryByEcosystemRow
	for rows.Next() {
		var i GetScanDependencySummaryByEcosystemRow
		if err := rows.Scan(&i.Ecosystem, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanDependencySummaryByLanguage = `-- name: GetScanDependencySummaryByLanguage :many
SELECT
    language,
    COUNT(*)::int AS total,
    COUNT(*) FILTER (WHERE is_vulnerable)::int AS vulnerable,
    COUNT(*) FILTER (WHERE is_outdated)::int AS outdated,
    COUNT(*) FILTER (WHERE has_license_issue)::int AS license_issues,
    COUNT(*) FILTER (WHERE cve_severity = 'CRITICAL')::int AS critical,
    COUNT(*) FILTER (WHERE cve_severity = 'HIGH')::int AS high,
    COUNT(*) FILTER (WHERE cve_severity = 'MEDIUM')::int AS medium,
    COUNT(*) FILTER (WHERE cve_severity = 'LOW')::int AS low
FROM scan_dependency_results
WHERE scan_id = $1
GROUP BY language
ORDER BY language ASC
`

type GetScanDependencySummaryByLanguageRow struct {
	Language      string `json:"language"`
	Total         int32  `json:"total"`
	Vulnerable    int32  `json:"vulnerable"`
	Outdated      int32  `json:"outdated"`
	LicenseIssues int32  `json:"license_issues"`
	Critical      int32  `json:"critical"`
	High          int32  `json:"high"`
	Medium        int32  `json:"medium"`
	Low           int32  `json:"low"`
}

func (q *Queries) GetScanDependencySummaryByLanguage(ctx context.Context, scanID uuid.UUID) ([]GetScanDependencySummaryByLanguageRow, error) {
	rows, err := q.db.Query(ctx, getScanDependencySummaryByLanguage, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScanDependencySummaryByLanguageRow
	for rows.Next() {
		var i GetScanDependencySummaryByLanguageRow
		if err := rows.Scan(
			&i.Language,
			&i.Total,
			&i.Vulnerable,
			&i.Outdated,
			&i.LicenseIssues,
			&i.Critical,
			&i.High,
			&i.Medium,
			&i.Low,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScanSonarResult = `-- name: GetScanSonarResult :one
SELECT id, scan_id, quality_gate, bugs, vulnerabilities, code_smells, coverage, duplications, security_hotspots, raw_response, created_at, analysis_id FROM scan_sonar_results
WHERE scan_id = $1
`

func (q *Queries) GetScanSonarResult(ctx context.Context, scanID uuid.UUID) (ScanSonarResult, error) {
	row := q.db.QueryRow(ctx, getScanSonarResult, scanID)
	var i ScanSonarResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.QualityGate,
		&i.Bugs,
		&i.Vulnerabilities,
		&i.CodeSmells,
		&i.Coverage,
		&i.Duplications,
		&i.SecurityHotspots,
		&i.RawResponse,
		&i.CreatedAt,
		&i.AnalysisID,
	)
	return i, err
}

const getUnifiedScan = `-- name: GetUnifiedScan :one
SELECT id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key FROM scans
WHERE id = $1
`

func (q *Queries) GetUnifiedScan(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, getUnifiedScan, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const listScanDependencyResults = `-- name: ListScanDependencyResults :many
SELECT id, scan_id, tool, finding_key, package_name, ecosystem, installed_version, fixed_version, latest_version, cve_id, cve_severity, license, is_outdated, is_vulnerable, has_license_issue, description, raw_finding, created_at, language FROM scan_dependency_results
WHERE scan_id = $1
  AND ($2::text = '' OR tool = $2)
  AND ($3::text = '' OR cve_severity = $3)
  AND ($4::text[] IS NULL OR cardinality($4::text[]) = 0 OR ecosystem = ANY($4::text[]))
  AND ($5::text[] IS NULL OR cardinality($5::text[]) = 0 OR language = ANY($5::text[]))
  AND (NOT $6::boolean OR is_outdated)
  AND (NOT $7::boolean OR is_vulnerable)
ORDER BY created_at DESC
LIMIT $8 OFFSET $9
`

type ListScanDependencyResultsParams struct {
	ScanID  uuid.UUID `json:"scan_id"`
	Column2 string    `json:"column_2"`
	Column3 string    `json:"column_3"`
	Column4 []string  `json:"column_4"`
	Column5 []string  `json:"column_5"`
	Column6 bool      `json:"column_6"`
	Column7 bool      `json:"column_7"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListScanDependencyResults(ctx context.Context, arg ListScanDependencyResultsParams) ([]ScanDependencyResult, error) {
	rows, err := q.db.Query(ctx, listScanDependencyResults,
		arg.ScanID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanDependencyResult
	for rows.Next() {
		var i ScanDependencyResult
		if err := rows.Scan(
			&i.ID,
			&i.ScanID,
			&i.Tool,
			&i.FindingKey,
			&i.PackageName,
			&i.Ecosystem,
			&i.InstalledVersion,
			&i.FixedVersion,
			&i.LatestVersion,
			&i.CveID,
			&i.CveSeverity,
			&i.License,
			&i.IsOutdated,
			&i.IsVulnerable,
			&i.HasLicenseIssue,
			&i.Description,
			&i.RawFinding,
			&i.CreatedAt,
			&i.Language,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsByRepository = `-- name: ListSnapshotsByRepository :many
SELECT id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at FROM repository_snapshots
WHERE repository_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSnapshotsByRepository(ctx context.Context, repositoryID uuid.UUID) ([]RepositorySnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshotsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepositorySnapshot
	for rows.Next() {
		var i RepositorySnapshot
		if err := rows.Scan(
			&i.ID,
			&i.RepositoryID,
			&i.BranchName,
			&i.CommitSha,
			&i.SourceSnapshotHash,
			&i.DependencyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnifiedProjectScans = `-- name: ListUnifiedProjectScans :many
SELECT id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key FROM scans
WHERE project_key = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUnifiedProjectScansParams struct {
	ProjectKey string `json:"project_key"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListUnifiedProjectScans(ctx context.Context, arg ListUnifiedProjectScansParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listUnifiedProjectScans, arg.ProjectKey, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.RepositoryID,
			&i.RepositorySnapshotID,
			&i.RepositoryUrl,
			&i.SourceDir,
			&i.Branch,
			&i.CommitSha,
			&i.SourceHash,
			&i.ScanConfigHash,
			&i.UserID,
			&i.Status,
			&i.SonarqubeStatus,
			&i.OwaspStatus,
			&i.TrivyStatus,
			&i.Progress,
			&i.ErrorMessage,
			&i.SonarqubeError,
			&i.OwaspError,
			&i.TrivyError,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloneStatus,
			&i.CloneError,
			&i.SonarProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnifiedUserScans = `-- name: ListUnifiedUserScans :many
SELECT id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key FROM scans
WHERE user_id = $1
  AND ($2::text = '' OR project_key = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListUnifiedUserScansParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Column2 string    `json:"column_2"`
	Limit   int32     `json:"limit"`
	Offset  int32     `json:"offset"`
}

func (q *Queries) ListUnifiedUserScans(ctx context.Context, arg ListUnifiedUserScansParams) ([]Scan, error) {
	rows, err := q.db.Query(ctx, listUnifiedUserScans,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scan
	for rows.Next() {
		var i Scan
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.RepositoryID,
			&i.RepositorySnapshotID,
			&i.RepositoryUrl,
			&i.SourceDir,
			&i.Branch,
			&i.CommitSha,
			&i.SourceHash,
			&i.ScanConfigHash,
			&i.UserID,
			&i.Status,
			&i.SonarqubeStatus,
			&i.OwaspStatus,
			&i.TrivyStatus,
			&i.Progress,
			&i.ErrorMessage,
			&i.SonarqubeError,
			&i.OwaspError,
			&i.TrivyError,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CloneStatus,
			&i.CloneError,
			&i.SonarProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUnifiedScanFinished = `-- name: MarkUnifiedScanFinished :one
UPDATE scans
SET finished_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

func (q *Queries) MarkUnifiedScanFinished(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, markUnifiedScanFinished, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const markUnifiedScanStarted = `-- name: MarkUnifiedScanStarted :one
UPDATE scans
SET status = 'IN_PROGRESS',
    started_at = COALESCE(started_at, now()),
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

func (q *Queries) MarkUnifiedScanStarted(ctx context.Context, id uuid.UUID) (Scan, error) {
	row := q.db.QueryRow(ctx, markUnifiedScanStarted, id)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateRepositorySnapshotDependencyHash = `-- name: UpdateRepositorySnapshotDependencyHash :one
UPDATE repository_snapshots
SET dependency_hash = $2
WHERE id = $1
RETURNING id, repository_id, branch_name, commit_sha, source_snapshot_hash, dependency_hash, created_at
`

type UpdateRepositorySnapshotDependencyHashParams struct {
	ID             uuid.UUID   `json:"id"`
	DependencyHash pgtype.Text `json:"dependency_hash"`
}

func (q *Queries) UpdateRepositorySnapshotDependencyHash(ctx context.Context, arg UpdateRepositorySnapshotDependencyHashParams) (RepositorySnapshot, error) {
	row := q.db.QueryRow(ctx, updateRepositorySnapshotDependencyHash, arg.ID, arg.DependencyHash)
	var i RepositorySnapshot
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.BranchName,
		&i.CommitSha,
		&i.SourceSnapshotHash,
		&i.DependencyHash,
		&i.CreatedAt,
	)
	return i, err
}

const updateUnifiedScanClonePhase = `-- name: UpdateUnifiedScanClonePhase :one
UPDATE scans
SET clone_status = $2,
    clone_error = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanClonePhaseParams struct {
	ID          uuid.UUID   `json:"id"`
	CloneStatus string      `json:"clone_status"`
	CloneError  pgtype.Text `json:"clone_error"`
}

func (q *Queries) UpdateUnifiedScanClonePhase(ctx context.Context, arg UpdateUnifiedScanClonePhaseParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanClonePhase, arg.ID, arg.CloneStatus, arg.CloneError)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanOwaspPhase = `-- name: UpdateUnifiedScanOwaspPhase :one
UPDATE scans
SET owasp_status = $2,
    owasp_error = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanOwaspPhaseParams struct {
	ID          uuid.UUID   `json:"id"`
	OwaspStatus string      `json:"owasp_status"`
	OwaspError  pgtype.Text `json:"owasp_error"`
}

func (q *Queries) UpdateUnifiedScanOwaspPhase(ctx context.Context, arg UpdateUnifiedScanOwaspPhaseParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanOwaspPhase, arg.ID, arg.OwaspStatus, arg.OwaspError)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanProgress = `-- name: UpdateUnifiedScanProgress :one
UPDATE scans
SET progress = GREATEST(progress, $2),
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanProgressParams struct {
	ID       uuid.UUID `json:"id"`
	Progress int32     `json:"progress"`
}

func (q *Queries) UpdateUnifiedScanProgress(ctx context.Context, arg UpdateUnifiedScanProgressParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanProgress, arg.ID, arg.Progress)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanSonarProjectKey = `-- name: UpdateUnifiedScanSonarProjectKey :one
UPDATE scans
SET sonar_project_key = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanSonarProjectKeyParams struct {
	ID              uuid.UUID   `json:"id"`
	SonarProjectKey pgtype.Text `json:"sonar_project_key"`
}

func (q *Queries) UpdateUnifiedScanSonarProjectKey(ctx context.Context, arg UpdateUnifiedScanSonarProjectKeyParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanSonarProjectKey, arg.ID, arg.SonarProjectKey)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanSonarqubePhase = `-- name: UpdateUnifiedScanSonarqubePhase :one
UPDATE scans
SET sonarqube_status = $2,
    sonarqube_error = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanSonarqubePhaseParams struct {
	ID              uuid.UUID   `json:"id"`
	SonarqubeStatus string      `json:"sonarqube_status"`
	SonarqubeError  pgtype.Text `json:"sonarqube_error"`
}

func (q *Queries) UpdateUnifiedScanSonarqubePhase(ctx context.Context, arg UpdateUnifiedScanSonarqubePhaseParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanSonarqubePhase, arg.ID, arg.SonarqubeStatus, arg.SonarqubeError)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanStatus = `-- name: UpdateUnifiedScanStatus :one
UPDATE scans
SET status = $2,
    error_message = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateUnifiedScanStatus(ctx context.Context, arg UpdateUnifiedScanStatusParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const updateUnifiedScanTrivyPhase = `-- name: UpdateUnifiedScanTrivyPhase :one
UPDATE scans
SET trivy_status = $2,
    trivy_error = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, project_key, repository_id, repository_snapshot_id, repository_url, source_dir, branch, commit_sha, source_hash, scan_config_hash, user_id, status, sonarqube_status, owasp_status, trivy_status, progress, error_message, sonarqube_error, owasp_error, trivy_error, started_at, finished_at, created_at, updated_at, clone_status, clone_error, sonar_project_key
`

type UpdateUnifiedScanTrivyPhaseParams struct {
	ID          uuid.UUID   `json:"id"`
	TrivyStatus string      `json:"trivy_status"`
	TrivyError  pgtype.Text `json:"trivy_error"`
}

func (q *Queries) UpdateUnifiedScanTrivyPhase(ctx context.Context, arg UpdateUnifiedScanTrivyPhaseParams) (Scan, error) {
	row := q.db.QueryRow(ctx, updateUnifiedScanTrivyPhase, arg.ID, arg.TrivyStatus, arg.TrivyError)
	var i Scan
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.RepositoryID,
		&i.RepositorySnapshotID,
		&i.RepositoryUrl,
		&i.SourceDir,
		&i.Branch,
		&i.CommitSha,
		&i.SourceHash,
		&i.ScanConfigHash,
		&i.UserID,
		&i.Status,
		&i.SonarqubeStatus,
		&i.OwaspStatus,
		&i.TrivyStatus,
		&i.Progress,
		&i.ErrorMessage,
		&i.SonarqubeError,
		&i.OwaspError,
		&i.TrivyError,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CloneStatus,
		&i.CloneError,
		&i.SonarProjectKey,
	)
	return i, err
}

const upsertScanDependencyResult = `-- name: UpsertScanDependencyResult :one
INSERT INTO scan_dependency_results (
    scan_id,
    tool,
    finding_key,
    language,
    package_name,
    ecosystem,
    installed_version,
    fixed_version,
    latest_version,
    cve_id,
    cve_severity,
    license,
    is_outdated,
    is_vulnerable,
    has_license_issue,
    description,
    raw_finding
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (scan_id, finding_key) DO UPDATE SET
    tool = EXCLUDED.tool,
    language = EXCLUDED.language,
    package_name = EXCLUDED.package_name,
    ecosystem = EXCLUDED.ecosystem,
    installed_version = EXCLUDED.installed_version,
    fixed_version = EXCLUDED.fixed_version,
    latest_version = EXCLUDED.latest_version,
    cve_id = EXCLUDED.cve_id,
    cve_severity = EXCLUDED.cve_severity,
    license = EXCLUDED.license,
    is_outdated = EXCLUDED.is_outdated,
    is_vulnerable = EXCLUDED.is_vulnerable,
    has_license_issue = EXCLUDED.has_license_issue,
    description = EXCLUDED.description,
    raw_finding = EXCLUDED.raw_finding
RETURNING id, scan_id, tool, finding_key, package_name, ecosystem, installed_version, fixed_version, latest_version, cve_id, cve_severity, license, is_outdated, is_vulnerable, has_license_issue, description, raw_finding, created_at, language
`

type UpsertScanDependencyResultParams struct {
	ScanID           uuid.UUID       `json:"scan_id"`
	Tool             string          `json:"tool"`
	FindingKey       string          `json:"finding_key"`
	Language         string          `json:"language"`
	PackageName      string          `json:"package_name"`
	Ecosystem        pgtype.Text     `json:"ecosystem"`
	InstalledVersion pgtype.Text     `json:"installed_version"`
	FixedVersion     pgtype.Text     `json:"fixed_version"`
	LatestVersion    pgtype.Text     `json:"latest_version"`
	CveID            pgtype.Text     `json:"cve_id"`
	CveSeverity      pgtype.Text     `json:"cve_severity"`
	License          pgtype.Text     `json:"license"`
	IsOutdated       bool            `json:"is_outdated"`
	IsVulnerable     bool            `json:"is_vulnerable"`
	HasLicenseIssue  bool            `json:"has_license_issue"`
	Description      pgtype.Text     `json:"description"`
	RawFinding       json.RawMessage `json:"raw_finding"`
}

func (q *Queries) UpsertScanDependencyResult(ctx context.Context, arg UpsertScanDependencyResultParams) (ScanDependencyResult, error) {
	row := q.db.QueryRow(ctx, upsertScanDependencyResult,
		arg.ScanID,
		arg.Tool,
		arg.FindingKey,
		arg.Language,
		arg.PackageName,
		arg.Ecosystem,
		arg.InstalledVersion,
		arg.FixedVersion,
		arg.LatestVersion,
		arg.CveID,
		arg.CveSeverity,
		arg.License,
		arg.IsOutdated,
		arg.IsVulnerable,
		arg.HasLicenseIssue,
		arg.Description,
		arg.RawFinding,
	)
	var i ScanDependencyResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.Tool,
		&i.FindingKey,
		&i.PackageName,
		&i.Ecosystem,
		&i.InstalledVersion,
		&i.FixedVersion,
		&i.LatestVersion,
		&i.CveID,
		&i.CveSeverity,
		&i.License,
		&i.IsOutdated,
		&i.IsVulnerable,
		&i.HasLicenseIssue,
		&i.Description,
		&i.RawFinding,
		&i.CreatedAt,
		&i.Language,
	)
	return i, err
}

const upsertScanSonarResult = `-- name: UpsertScanSonarResult :one
INSERT INTO scan_sonar_results (
    scan_id,
    analysis_id,
    quality_gate,
    bugs,
    vulnerabilities,
    code_smells,
    coverage,
    duplications,
    security_hotspots,
    raw_response
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (scan_id) DO UPDATE SET
    analysis_id = EXCLUDED.analysis_id,
    quality_gate = EXCLUDED.quality_gate,
    bugs = EXCLUDED.bugs,
    vulnerabilities = EXCLUDED.vulnerabilities,
    code_smells = EXCLUDED.code_smells,
    coverage = EXCLUDED.coverage,
    duplications = EXCLUDED.duplications,
    security_hotspots = EXCLUDED.security_hotspots,
    raw_response = EXCLUDED.raw_response
RETURNING id, scan_id, quality_gate, bugs, vulnerabilities, code_smells, coverage, duplications, security_hotspots, raw_response, created_at, analysis_id
`

type UpsertScanSonarResultParams struct {
	ScanID           uuid.UUID       `json:"scan_id"`
	AnalysisID       pgtype.Text     `json:"analysis_id"`
	QualityGate      string          `json:"quality_gate"`
	Bugs             int32           `json:"bugs"`
	Vulnerabilities  int32           `json:"vulnerabilities"`
	CodeSmells       int32           `json:"code_smells"`
	Coverage         float64         `json:"coverage"`
	Duplications     float64         `json:"duplications"`
	SecurityHotspots int32           `json:"security_hotspots"`
	RawResponse      json.RawMessage `json:"raw_response"`
}

func (q *Queries) UpsertScanSonarResult(ctx context.Context, arg UpsertScanSonarResultParams) (ScanSonarResult, error) {
	row := q.db.QueryRow(ctx, upsertScanSonarResult,
		arg.ScanID,
		arg.AnalysisID,
		arg.QualityGate,
		arg.Bugs,
		arg.Vulnerabilities,
		arg.CodeSmells,
		arg.Coverage,
		arg.Duplications,
		arg.SecurityHotspots,
		arg.RawResponse,
	)
	var i ScanSonarResult
	err := row.Scan(
		&i.ID,
		&i.ScanID,
		&i.QualityGate,
		&i.Bugs,
		&i.Vulnerabilities,
		&i.CodeSmells,
		&i.Coverage,
		&i.Duplications,
		&i.SecurityHotspots,
		&i.RawResponse,
		&i.CreatedAt,
		&i.AnalysisID,
	)
	return i, err
}
