// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFindingsByJobAndSeverity = `-- name: CountFindingsByJobAndSeverity :many
SELECT severity, COUNT(*) AS count
FROM findings
WHERE job_id = $1
GROUP BY severity
`

type CountFindingsByJobAndSeverityRow struct {
	Severity NullSeverityLevel `json:"severity"`
	Count    int64             `json:"count"`
}

func (q *Queries) CountFindingsByJobAndSeverity(ctx context.Context, jobID uuid.UUID) ([]CountFindingsByJobAndSeverityRow, error) {
	rows, err := q.db.Query(ctx, countFindingsByJobAndSeverity, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountFindingsByJobAndSeverityRow
	for rows.Next() {
		var i CountFindingsByJobAndSeverityRow
		if err := rows.Scan(&i.Severity, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAISuggestion = `-- name: CreateAISuggestion :one
INSERT INTO ai_suggestions (job_id, content)
VALUES ($1, $2)
RETURNING id, job_id, content, is_suggested, created_at, mode, provider, model, output_json, input_tokens, output_tokens, feedback, updated_at
`

type CreateAISuggestionParams struct {
	JobID   uuid.UUID `json:"job_id"`
	Content string    `json:"content"`
}

func (q *Queries) CreateAISuggestion(ctx context.Context, arg CreateAISuggestionParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, createAISuggestion, arg.JobID, arg.Content)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Content,
		&i.IsSuggested,
		&i.CreatedAt,
		&i.Mode,
		&i.Provider,
		&i.Model,
		&i.OutputJson,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Feedback,
		&i.UpdatedAt,
	)
	return i, err
}

const createFinding = `-- name: CreateFinding :one
INSERT INTO findings (project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at
`

type CreateFindingParams struct {
	ProjectID   uuid.UUID         `json:"project_id"`
	JobID       uuid.UUID         `json:"job_id"`
	StepID      uuid.UUID         `json:"step_id"`
	ToolID      uuid.UUID         `json:"tool_id"`
	Severity    NullSeverityLevel `json:"severity"`
	Title       pgtype.Text       `json:"title"`
	Host        pgtype.Text       `json:"host"`
	Port        pgtype.Int4       `json:"port"`
	Fingerprint pgtype.Text       `json:"fingerprint"`
	RawResultID pgtype.UUID       `json:"raw_result_id"`
}

func (q *Queries) CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, createFinding,
		arg.ProjectID,
		arg.JobID,
		arg.StepID,
		arg.ToolID,
		arg.Severity,
		arg.Title,
		arg.Host,
		arg.Port,
		arg.Fingerprint,
		arg.RawResultID,
	)
	var i Finding
	err := row.Scan(
		&i.FindingID,
		&i.ProjectID,
		&i.JobID,
		&i.StepID,
		&i.ToolID,
		&i.Severity,
		&i.Title,
		&i.Host,
		&i.Port,
		&i.Fingerprint,
		&i.RawResultID,
		&i.CreatedAt,
	)
	return i, err
}

const getAISuggestionByJobID = `-- name: GetAISuggestionByJobID :one
SELECT id, job_id, content, is_suggested, created_at, mode, provider, model, output_json, input_tokens, output_tokens, feedback, updated_at FROM ai_suggestions
WHERE job_id = $1
`

func (q *Queries) GetAISuggestionByJobID(ctx context.Context, jobID uuid.UUID) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, getAISuggestionByJobID, jobID)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Content,
		&i.IsSuggested,
		&i.CreatedAt,
		&i.Mode,
		&i.Provider,
		&i.Model,
		&i.OutputJson,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Feedback,
		&i.UpdatedAt,
	)
	return i, err
}

const getFindingByID = `-- name: GetFindingByID :one
SELECT finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at FROM findings
WHERE finding_id = $1
`

func (q *Queries) GetFindingByID(ctx context.Context, findingID uuid.UUID) (Finding, error) {
	row := q.db.QueryRow(ctx, getFindingByID, findingID)
	var i Finding
	err := row.Scan(
		&i.FindingID,
		&i.ProjectID,
		&i.JobID,
		&i.StepID,
		&i.ToolID,
		&i.Severity,
		&i.Title,
		&i.Host,
		&i.Port,
		&i.Fingerprint,
		&i.RawResultID,
		&i.CreatedAt,
	)
	return i, err
}

const listFindingsByJob = `-- name: ListFindingsByJob :many
SELECT finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at FROM findings
WHERE job_id = $1
ORDER BY severity DESC, created_at DESC
`

func (q *Queries) ListFindingsByJob(ctx context.Context, jobID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.FindingID,
			&i.ProjectID,
			&i.JobID,
			&i.StepID,
			&i.ToolID,
			&i.Severity,
			&i.Title,
			&i.Host,
			&i.Port,
			&i.Fingerprint,
			&i.RawResultID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsByProject = `-- name: ListFindingsByProject :many
SELECT finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at FROM findings
WHERE project_id = $1
ORDER BY severity DESC, created_at DESC
`

func (q *Queries) ListFindingsByProject(ctx context.Context, projectID uuid.UUID) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.FindingID,
			&i.ProjectID,
			&i.JobID,
			&i.StepID,
			&i.ToolID,
			&i.Severity,
			&i.Title,
			&i.Host,
			&i.Port,
			&i.Fingerprint,
			&i.RawResultID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFindingsBySeverity = `-- name: ListFindingsBySeverity :many
SELECT finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at FROM findings
WHERE job_id = $1 AND severity = $2
ORDER BY created_at DESC
`

type ListFindingsBySeverityParams struct {
	JobID    uuid.UUID         `json:"job_id"`
	Severity NullSeverityLevel `json:"severity"`
}

func (q *Queries) ListFindingsBySeverity(ctx context.Context, arg ListFindingsBySeverityParams) ([]Finding, error) {
	rows, err := q.db.Query(ctx, listFindingsBySeverity, arg.JobID, arg.Severity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finding
	for rows.Next() {
		var i Finding
		if err := rows.Scan(
			&i.FindingID,
			&i.ProjectID,
			&i.JobID,
			&i.StepID,
			&i.ToolID,
			&i.Severity,
			&i.Title,
			&i.Host,
			&i.Port,
			&i.Fingerprint,
			&i.RawResultID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAISuggestion = `-- name: UpdateAISuggestion :one
UPDATE ai_suggestions
SET
    content      = $2,
    is_suggested = $3
WHERE job_id = $1
RETURNING id, job_id, content, is_suggested, created_at, mode, provider, model, output_json, input_tokens, output_tokens, feedback, updated_at
`

type UpdateAISuggestionParams struct {
	JobID       uuid.UUID   `json:"job_id"`
	Content     string      `json:"content"`
	IsSuggested pgtype.Bool `json:"is_suggested"`
}

func (q *Queries) UpdateAISuggestion(ctx context.Context, arg UpdateAISuggestionParams) (AiSuggestion, error) {
	row := q.db.QueryRow(ctx, updateAISuggestion, arg.JobID, arg.Content, arg.IsSuggested)
	var i AiSuggestion
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Content,
		&i.IsSuggested,
		&i.CreatedAt,
		&i.Mode,
		&i.Provider,
		&i.Model,
		&i.OutputJson,
		&i.InputTokens,
		&i.OutputTokens,
		&i.Feedback,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertFinding = `-- name: UpsertFinding :one
INSERT INTO findings (project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (job_id, tool_id, fingerprint)
DO UPDATE SET
    severity      = EXCLUDED.severity,
    title         = EXCLUDED.title,
    raw_result_id = EXCLUDED.raw_result_id
RETURNING finding_id, project_id, job_id, step_id, tool_id, severity, title, host, port, fingerprint, raw_result_id, created_at
`

type UpsertFindingParams struct {
	ProjectID   uuid.UUID         `json:"project_id"`
	JobID       uuid.UUID         `json:"job_id"`
	StepID      uuid.UUID         `json:"step_id"`
	ToolID      uuid.UUID         `json:"tool_id"`
	Severity    NullSeverityLevel `json:"severity"`
	Title       pgtype.Text       `json:"title"`
	Host        pgtype.Text       `json:"host"`
	Port        pgtype.Int4       `json:"port"`
	Fingerprint pgtype.Text       `json:"fingerprint"`
	RawResultID pgtype.UUID       `json:"raw_result_id"`
}

func (q *Queries) UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error) {
	row := q.db.QueryRow(ctx, upsertFinding,
		arg.ProjectID,
		arg.JobID,
		arg.StepID,
		arg.ToolID,
		arg.Severity,
		arg.Title,
		arg.Host,
		arg.Port,
		arg.Fingerprint,
		arg.RawResultID,
	)
	var i Finding
	err := row.Scan(
		&i.FindingID,
		&i.ProjectID,
		&i.JobID,
		&i.StepID,
		&i.ToolID,
		&i.Severity,
		&i.Title,
		&i.Host,
		&i.Port,
		&i.Fingerprint,
		&i.RawResultID,
		&i.CreatedAt,
	)
	return i, err
}
