// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExecutionMode string

const (
	ExecutionModeCli  ExecutionMode = "cli"
	ExecutionModeCicd ExecutionMode = "cicd"
	ExecutionModeWeb  ExecutionMode = "web"
)

func (e *ExecutionMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionMode(s)
	case string:
		*e = ExecutionMode(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionMode: %T", src)
	}
	return nil
}

type NullExecutionMode struct {
	ExecutionMode ExecutionMode `json:"execution_mode"`
	Valid         bool          `json:"valid"` // Valid is true if ExecutionMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionMode) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionMode), nil
}

type InputSourceType string

const (
	InputSourceTypeTarget InputSourceType = "target"
	InputSourceTypeStep   InputSourceType = "step"
)

func (e *InputSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InputSourceType(s)
	case string:
		*e = InputSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InputSourceType: %T", src)
	}
	return nil
}

type NullInputSourceType struct {
	InputSourceType InputSourceType `json:"input_source_type"`
	Valid           bool            `json:"valid"` // Valid is true if InputSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInputSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.InputSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InputSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInputSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InputSourceType), nil
}

type ProviderAccountStatus string

const (
	ProviderAccountStatusCONNECTED    ProviderAccountStatus = "CONNECTED"
	ProviderAccountStatusDISCONNECTED ProviderAccountStatus = "DISCONNECTED"
	ProviderAccountStatusREVOKED      ProviderAccountStatus = "REVOKED"
)

func (e *ProviderAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderAccountStatus(s)
	case string:
		*e = ProviderAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderAccountStatus: %T", src)
	}
	return nil
}

type NullProviderAccountStatus struct {
	ProviderAccountStatus ProviderAccountStatus `json:"provider_account_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if ProviderAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderAccountStatus), nil
}

type ProviderTypeEnum string

const (
	ProviderTypeEnumGithub    ProviderTypeEnum = "github"
	ProviderTypeEnumGitlab    ProviderTypeEnum = "gitlab"
	ProviderTypeEnumBitbucket ProviderTypeEnum = "bitbucket"
)

func (e *ProviderTypeEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderTypeEnum(s)
	case string:
		*e = ProviderTypeEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderTypeEnum: %T", src)
	}
	return nil
}

type NullProviderTypeEnum struct {
	ProviderTypeEnum ProviderTypeEnum `json:"provider_type_enum"`
	Valid            bool             `json:"valid"` // Valid is true if ProviderTypeEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderTypeEnum) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderTypeEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderTypeEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderTypeEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderTypeEnum), nil
}

type ReportScopeType string

const (
	ReportScopeTypeProject ReportScopeType = "project"
	ReportScopeTypeTarget  ReportScopeType = "target"
	ReportScopeTypeJob     ReportScopeType = "job"
)

func (e *ReportScopeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReportScopeType(s)
	case string:
		*e = ReportScopeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReportScopeType: %T", src)
	}
	return nil
}

type NullReportScopeType struct {
	ReportScopeType ReportScopeType `json:"report_scope_type"`
	Valid           bool            `json:"valid"` // Valid is true if ReportScopeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReportScopeType) Scan(value interface{}) error {
	if value == nil {
		ns.ReportScopeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReportScopeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReportScopeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReportScopeType), nil
}

type ScanJobStatus string

const (
	ScanJobStatusPending   ScanJobStatus = "pending"
	ScanJobStatusRunning   ScanJobStatus = "running"
	ScanJobStatusCompleted ScanJobStatus = "completed"
	ScanJobStatusFailed    ScanJobStatus = "failed"
)

func (e *ScanJobStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanJobStatus(s)
	case string:
		*e = ScanJobStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanJobStatus: %T", src)
	}
	return nil
}

type NullScanJobStatus struct {
	ScanJobStatus ScanJobStatus `json:"scan_job_status"`
	Valid         bool          `json:"valid"` // Valid is true if ScanJobStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanJobStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanJobStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanJobStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanJobStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanJobStatus), nil
}

type ScanStepStatus string

const (
	ScanStepStatusPending   ScanStepStatus = "pending"
	ScanStepStatusRunning   ScanStepStatus = "running"
	ScanStepStatusCompleted ScanStepStatus = "completed"
	ScanStepStatusFailed    ScanStepStatus = "failed"
	ScanStepStatusSkipped   ScanStepStatus = "skipped"
)

func (e *ScanStepStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScanStepStatus(s)
	case string:
		*e = ScanStepStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ScanStepStatus: %T", src)
	}
	return nil
}

type NullScanStepStatus struct {
	ScanStepStatus ScanStepStatus `json:"scan_step_status"`
	Valid          bool           `json:"valid"` // Valid is true if ScanStepStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScanStepStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ScanStepStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScanStepStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScanStepStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScanStepStatus), nil
}

type SeverityLevel string

const (
	SeverityLevelInfo     SeverityLevel = "info"
	SeverityLevelLow      SeverityLevel = "low"
	SeverityLevelMedium   SeverityLevel = "medium"
	SeverityLevelHigh     SeverityLevel = "high"
	SeverityLevelCritical SeverityLevel = "critical"
)

func (e *SeverityLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SeverityLevel(s)
	case string:
		*e = SeverityLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SeverityLevel: %T", src)
	}
	return nil
}

type NullSeverityLevel struct {
	SeverityLevel SeverityLevel `json:"severity_level"`
	Valid         bool          `json:"valid"` // Valid is true if SeverityLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeverityLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SeverityLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SeverityLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeverityLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SeverityLevel), nil
}

type AiSuggestion struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	Content      string             `json:"content"`
	IsSuggested  pgtype.Bool        `json:"is_suggested"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Mode         string             `json:"mode"`
	Provider     string             `json:"provider"`
	Model        string             `json:"model"`
	OutputJson   json.RawMessage    `json:"output_json"`
	InputTokens  int32              `json:"input_tokens"`
	OutputTokens int32              `json:"output_tokens"`
	Feedback     string             `json:"feedback"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ApiKey struct {
	KeyID        uuid.UUID          `json:"key_id"`
	ProjectID    uuid.UUID          `json:"project_id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         pgtype.Text        `json:"name"`
	Prefix       pgtype.Text        `json:"prefix"`
	Description  pgtype.Text        `json:"description"`
	HashedSecret string             `json:"hashed_secret"`
	Scopes       []string           `json:"scopes"`
	IsActive     pgtype.Bool        `json:"is_active"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	ExpiredAt    pgtype.Timestamptz `json:"expired_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	DocumentID     uuid.UUID          `json:"document_id"`
	DefaultLocale  pgtype.Text        `json:"default_locale"`
	IsPublish      pgtype.Bool        `json:"is_publish"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}

type DocumentTranslation struct {
	TranslationID  uuid.UUID          `json:"translation_id"`
	DocumentID     uuid.UUID          `json:"document_id"`
	Locale         string             `json:"locale"`
	Title          pgtype.Text        `json:"title"`
	Content        pgtype.Text        `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastModifiedAt pgtype.Timestamptz `json:"last_modified_at"`
}

type Finding struct {
	FindingID   uuid.UUID          `json:"finding_id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	JobID       uuid.UUID          `json:"job_id"`
	StepID      uuid.UUID          `json:"step_id"`
	ToolID      uuid.UUID          `json:"tool_id"`
	Severity    NullSeverityLevel  `json:"severity"`
	Title       pgtype.Text        `json:"title"`
	Host        pgtype.Text        `json:"host"`
	Port        pgtype.Int4        `json:"port"`
	Fingerprint pgtype.Text        `json:"fingerprint"`
	RawResultID pgtype.UUID        `json:"raw_result_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ProjectID    uuid.UUID          `json:"project_id"`
	UserID       uuid.UUID          `json:"user_id"`
	ProjectName  string             `json:"project_name"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastModified pgtype.Timestamptz `json:"last_modified"`
}

type ProviderAccount struct {
	ID                    uuid.UUID             `json:"id"`
	UserID                uuid.UUID             `json:"user_id"`
	ProviderType          ProviderTypeEnum      `json:"provider_type"`
	ProviderAccountID     string                `json:"provider_account_id"`
	ProviderUsername      string                `json:"provider_username"`
	ProviderEmail         pgtype.Text           `json:"provider_email"`
	Status                ProviderAccountStatus `json:"status"`
	ConnectedAt           pgtype.Timestamptz    `json:"connected_at"`
	UpdatedAt             pgtype.Timestamptz    `json:"updated_at"`
	AccessTokenEncrypted  string                `json:"access_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text           `json:"refresh_token_encrypted"`
}

type Report struct {
	ReportID      uuid.UUID          `json:"report_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	ScopeID       uuid.UUID          `json:"scope_id"`
	ScopeType     ReportScopeType    `json:"scope_type"`
	DocumentID    pgtype.UUID        `json:"document_id"`
	FileName      pgtype.Text        `json:"file_name"`
	FileExtension pgtype.Text        `json:"file_extension"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Repository struct {
	ID                     uuid.UUID          `json:"id"`
	UserID                 uuid.UUID          `json:"user_id"`
	ProviderAccountID      uuid.UUID          `json:"provider_account_id"`
	ProviderRepositoryID   pgtype.Text        `json:"provider_repository_id"`
	FullName               string             `json:"full_name"`
	RepositoryIdentityHash string             `json:"repository_identity_hash"`
	IsPrivate              bool               `json:"is_private"`
	DefaultBranch          string             `json:"default_branch"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RepositorySnapshot struct {
	ID                 uuid.UUID          `json:"id"`
	RepositoryID       uuid.UUID          `json:"repository_id"`
	BranchName         string             `json:"branch_name"`
	CommitSha          string             `json:"commit_sha"`
	SourceSnapshotHash string             `json:"source_snapshot_hash"`
	DependencyHash     pgtype.Text        `json:"dependency_hash"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type Scan struct {
	ID                   uuid.UUID          `json:"id"`
	ProjectKey           string             `json:"project_key"`
	RepositoryID         pgtype.UUID        `json:"repository_id"`
	RepositorySnapshotID pgtype.UUID        `json:"repository_snapshot_id"`
	RepositoryUrl        pgtype.Text        `json:"repository_url"`
	SourceDir            string             `json:"source_dir"`
	Branch               pgtype.Text        `json:"branch"`
	CommitSha            pgtype.Text        `json:"commit_sha"`
	SourceHash           pgtype.Text        `json:"source_hash"`
	ScanConfigHash       pgtype.Text        `json:"scan_config_hash"`
	UserID               uuid.UUID          `json:"user_id"`
	Status               string             `json:"status"`
	SonarqubeStatus      string             `json:"sonarqube_status"`
	OwaspStatus          string             `json:"owasp_status"`
	TrivyStatus          string             `json:"trivy_status"`
	Progress             int32              `json:"progress"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	SonarqubeError       pgtype.Text        `json:"sonarqube_error"`
	OwaspError           pgtype.Text        `json:"owasp_error"`
	TrivyError           pgtype.Text        `json:"trivy_error"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	CloneStatus          string             `json:"clone_status"`
	CloneError           pgtype.Text        `json:"clone_error"`
	SonarProjectKey      pgtype.Text        `json:"sonar_project_key"`
}

type ScanDependencyResult struct {
	ID               uuid.UUID          `json:"id"`
	ScanID           uuid.UUID          `json:"scan_id"`
	Tool             string             `json:"tool"`
	FindingKey       string             `json:"finding_key"`
	PackageName      string             `json:"package_name"`
	Ecosystem        pgtype.Text        `json:"ecosystem"`
	InstalledVersion pgtype.Text        `json:"installed_version"`
	FixedVersion     pgtype.Text        `json:"fixed_version"`
	LatestVersion    pgtype.Text        `json:"latest_version"`
	CveID            pgtype.Text        `json:"cve_id"`
	CveSeverity      pgtype.Text        `json:"cve_severity"`
	License          pgtype.Text        `json:"license"`
	IsOutdated       bool               `json:"is_outdated"`
	IsVulnerable     bool               `json:"is_vulnerable"`
	HasLicenseIssue  bool               `json:"has_license_issue"`
	Description      pgtype.Text        `json:"description"`
	RawFinding       json.RawMessage    `json:"raw_finding"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Language         string             `json:"language"`
}

type ScanJob struct {
	JobID         uuid.UUID          `json:"job_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	TargetID      uuid.UUID          `json:"target_id"`
	TriggeredBy   pgtype.UUID        `json:"triggered_by"`
	ApiKeyID      pgtype.UUID        `json:"api_key_id"`
	Status        NullScanJobStatus  `json:"status"`
	ExecutionMode NullExecutionMode  `json:"execution_mode"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	ScanDuration  pgtype.Interval    `json:"scan_duration"`
}

type ScanPhase struct {
	ID         uuid.UUID          `json:"id"`
	ScanID     uuid.UUID          `json:"scan_id"`
	Phase      string             `json:"phase"`
	Status     string             `json:"status"`
	Progress   int32              `json:"progress"`
	Attempt    int32              `json:"attempt"`
	Error      pgtype.Text        `json:"error"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type ScanResult struct {
	ResultID   uuid.UUID          `json:"result_id"`
	StepID     uuid.UUID          `json:"step_id"`
	JobID      uuid.UUID          `json:"job_id"`
	ProjectID  uuid.UUID          `json:"project_id"`
	TargetID   uuid.UUID          `json:"target_id"`
	ToolID     uuid.UUID          `json:"tool_id"`
	RawData    []byte             `json:"raw_data"`
	ParsedData []byte             `json:"parsed_data"`
	Severity   NullSeverityLevel  `json:"severity"`
	Status     NullScanStepStatus `json:"status"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ScanSonarResult struct {
	ID               uuid.UUID          `json:"id"`
	ScanID           uuid.UUID          `json:"scan_id"`
	QualityGate      string             `json:"quality_gate"`
	Bugs             int32              `json:"bugs"`
	Vulnerabilities  int32              `json:"vulnerabilities"`
	CodeSmells       int32              `json:"code_smells"`
	Coverage         float64            `json:"coverage"`
	Duplications     float64            `json:"duplications"`
	SecurityHotspots int32              `json:"security_hotspots"`
	RawResponse      json.RawMessage    `json:"raw_response"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AnalysisID       pgtype.Text        `json:"analysis_id"`
}

type ScanStep struct {
	StepID      uuid.UUID          `json:"step_id"`
	JobID       uuid.UUID          `json:"job_id"`
	ToolID      uuid.UUID          `json:"tool_id"`
	ToolVersion pgtype.Text        `json:"tool_version"`
	InputSource InputSourceType    `json:"input_source"`
	InputStepID pgtype.UUID        `json:"input_step_id"`
	StepKey     string             `json:"step_key"`
	StepOrder   int32              `json:"step_order"`
	Status      NullScanStepStatus `json:"status"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ScanSuggestion struct {
	SuggestionID  uuid.UUID          `json:"suggestion_id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	JobID         uuid.UUID          `json:"job_id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Reasoning     pgtype.Text        `json:"reasoning"`
	Priority      pgtype.Text        `json:"priority"`
	Confidence    pgtype.Float8      `json:"confidence"`
	ToolID        uuid.UUID          `json:"tool_id"`
	InputStepID   pgtype.UUID        `json:"input_step_id"`
	Params        json.RawMessage    `json:"params"`
	Status        string             `json:"status"`
	ExecutedJobID pgtype.UUID        `json:"executed_job_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Target struct {
	TargetID    uuid.UUID          `json:"target_id"`
	ProjectID   uuid.UUID          `json:"project_id"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Tool struct {
	ToolID              uuid.UUID          `json:"tool_id"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	ToolName            string             `json:"tool_name"`
	ToolDescription     pgtype.Text        `json:"tool_description"`
	ToolLongDescription pgtype.Text        `json:"tool_long_description"`
	InputSchema         []byte             `json:"input_schema"`
	OutputSchema        []byte             `json:"output_schema"`
	ScanConfig          []byte             `json:"scan_config"`
	InstallMethod       pgtype.Text        `json:"install_method"`
	ImageRef            pgtype.Text        `json:"image_ref"`
	ImageSource         pgtype.Text        `json:"image_source"`
	IsActive            pgtype.Bool        `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	VersionID           uuid.UUID          `json:"version_id"`
	DeniedOptions       []string           `json:"denied_options"`
	Examples            json.RawMessage    `json:"examples"`
	// Shadow output configuration: {json_flag, file_flag, default_path, filename_template, alternative_formats, parse_timeout_seconds, fallback_to_stdout, is_streaming}
	ShadowOutputConfig []byte `json:"shadow_output_config"`
	ParserConfig       []byte `json:"parser_config"`
}

type ToolCategory struct {
	CategoryID   uuid.UUID          `json:"category_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	LastModified pgtype.Timestamptz `json:"last_modified"`
}

type User struct {
	UserID        uuid.UUID          `json:"user_id"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	AliasName     pgtype.Text        `json:"alias_name"`
	AvatarProfile pgtype.Text        `json:"avatar_profile"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	LastModified  pgtype.Timestamptz `json:"last_modified"`
}

type Version struct {
	VersionID     uuid.UUID          `json:"version_id"`
	VersionNumber string             `json:"version_number"`
	InstalledAt   pgtype.Timestamptz `json:"installed_at"`
}
