// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectsByUser = `-- name: CountProjectsByUser :one
SELECT COUNT(*) FROM projects
WHERE user_id = $1
`

func (q *Queries) CountProjectsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (user_id, project_name, description)
VALUES ($1, $2, $3)
RETURNING project_id, user_id, project_name, description, created_at, last_modified
`

type CreateProjectParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	ProjectName string      `json:"project_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.UserID, arg.ProjectName, arg.Description)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects
WHERE project_id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.Exec(ctx, deleteProject, arg.ProjectID, arg.UserID)
	return err
}

const deleteProjectFindings = `-- name: DeleteProjectFindings :exec
DELETE FROM findings
WHERE project_id = $1
`

func (q *Queries) DeleteProjectFindings(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectFindings, projectID)
	return err
}

const deleteProjectScanJobs = `-- name: DeleteProjectScanJobs :exec
DELETE FROM scan_jobs
WHERE project_id = $1
`

// scan_steps will be auto-deleted via ON DELETE CASCADE from scan_jobs
func (q *Queries) DeleteProjectScanJobs(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectScanJobs, projectID)
	return err
}

const deleteProjectScanResults = `-- name: DeleteProjectScanResults :exec
DELETE FROM scan_results
WHERE project_id = $1
`

func (q *Queries) DeleteProjectScanResults(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectScanResults, projectID)
	return err
}

const deleteProjectTargets = `-- name: DeleteProjectTargets :exec
DELETE FROM targets
WHERE project_id = $1
`

func (q *Queries) DeleteProjectTargets(ctx context.Context, projectID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectTargets, projectID)
	return err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT project_id, user_id, project_name, description, created_at, last_modified FROM projects
WHERE project_id = $1 AND user_id = $2
`

type GetProjectByIDParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ProjectID, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const getProjectByIDInternal = `-- name: GetProjectByIDInternal :one
SELECT project_id, user_id, project_name, description, created_at, last_modified FROM projects
WHERE project_id = $1
`

func (q *Queries) GetProjectByIDInternal(ctx context.Context, projectID uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDInternal, projectID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT project_id, user_id, project_name, description, created_at, last_modified FROM projects
WHERE project_name = $1 AND user_id = $2
`

type GetProjectByNameParams struct {
	ProjectName string    `json:"project_name"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.ProjectName, arg.UserID)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const listProjectsByUser = `-- name: ListProjectsByUser :many
SELECT project_id, user_id, project_name, description, created_at, last_modified FROM projects
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ProjectID,
			&i.UserID,
			&i.ProjectName,
			&i.Description,
			&i.CreatedAt,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
    project_name  = COALESCE($3, project_name),
    description   = COALESCE($4, description),
    last_modified = now()
WHERE project_id = $1 AND user_id = $2
RETURNING project_id, user_id, project_name, description, created_at, last_modified
`

type UpdateProjectParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	UserID      uuid.UUID   `json:"user_id"`
	ProjectName pgtype.Text `json:"project_name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ProjectID,
		arg.UserID,
		arg.ProjectName,
		arg.Description,
	)
	var i Project
	err := row.Scan(
		&i.ProjectID,
		&i.UserID,
		&i.ProjectName,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}
