// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_accounts.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProviderAccount = `-- name: CreateProviderAccount :one
INSERT INTO provider_accounts (
    user_id, provider_type, provider_account_id,
    provider_username, provider_email, status
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted
`

type CreateProviderAccountParams struct {
	UserID            uuid.UUID             `json:"user_id"`
	ProviderType      ProviderTypeEnum      `json:"provider_type"`
	ProviderAccountID string                `json:"provider_account_id"`
	ProviderUsername  string                `json:"provider_username"`
	ProviderEmail     pgtype.Text           `json:"provider_email"`
	Status            ProviderAccountStatus `json:"status"`
}

func (q *Queries) CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, createProviderAccount,
		arg.UserID,
		arg.ProviderType,
		arg.ProviderAccountID,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.Status,
	)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderAccountID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    user_id, provider_account_id, provider_repository_id,
    full_name, repository_identity_hash, is_private, default_branch
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at
`

type CreateRepositoryParams struct {
	UserID                 uuid.UUID   `json:"user_id"`
	ProviderAccountID      uuid.UUID   `json:"provider_account_id"`
	ProviderRepositoryID   pgtype.Text `json:"provider_repository_id"`
	FullName               string      `json:"full_name"`
	RepositoryIdentityHash string      `json:"repository_identity_hash"`
	IsPrivate              bool        `json:"is_private"`
	DefaultBranch          string      `json:"default_branch"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.UserID,
		arg.ProviderAccountID,
		arg.ProviderRepositoryID,
		arg.FullName,
		arg.RepositoryIdentityHash,
		arg.IsPrivate,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderAccountID,
		&i.ProviderRepositoryID,
		&i.FullName,
		&i.RepositoryIdentityHash,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProviderAccount = `-- name: DeleteProviderAccount :exec
DELETE FROM provider_accounts
WHERE id = $1
`

func (q *Queries) DeleteProviderAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProviderAccount, id)
	return err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories
WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const getProviderAccountByID = `-- name: GetProviderAccountByID :one
SELECT id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted FROM provider_accounts
WHERE id = $1
`

func (q *Queries) GetProviderAccountByID(ctx context.Context, id uuid.UUID) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccountByID, id)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderAccountID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
	)
	return i, err
}

const getProviderAccountByIdentity = `-- name: GetProviderAccountByIdentity :one
SELECT id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted FROM provider_accounts
WHERE provider_type = $1 AND provider_account_id = $2
`

type GetProviderAccountByIdentityParams struct {
	ProviderType      ProviderTypeEnum `json:"provider_type"`
	ProviderAccountID string           `json:"provider_account_id"`
}

func (q *Queries) GetProviderAccountByIdentity(ctx context.Context, arg GetProviderAccountByIdentityParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, getProviderAccountByIdentity, arg.ProviderType, arg.ProviderAccountID)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderAccountID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
	)
	return i, err
}

const getRepositoryByID = `-- name: GetRepositoryByID :one
SELECT id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at FROM repositories
WHERE id = $1
`

func (q *Queries) GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByID, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderAccountID,
		&i.ProviderRepositoryID,
		&i.FullName,
		&i.RepositoryIdentityHash,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByIdentityHash = `-- name: GetRepositoryByIdentityHash :one
SELECT id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at FROM repositories
WHERE repository_identity_hash = $1
`

func (q *Queries) GetRepositoryByIdentityHash(ctx context.Context, repositoryIdentityHash string) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByIdentityHash, repositoryIdentityHash)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderAccountID,
		&i.ProviderRepositoryID,
		&i.FullName,
		&i.RepositoryIdentityHash,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviderAccountsByUser = `-- name: ListProviderAccountsByUser :many
SELECT id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted FROM provider_accounts
WHERE user_id = $1
ORDER BY connected_at DESC
`

func (q *Queries) ListProviderAccountsByUser(ctx context.Context, userID uuid.UUID) ([]ProviderAccount, error) {
	rows, err := q.db.Query(ctx, listProviderAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderAccount
	for rows.Next() {
		var i ProviderAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderType,
			&i.ProviderAccountID,
			&i.ProviderUsername,
			&i.ProviderEmail,
			&i.Status,
			&i.ConnectedAt,
			&i.UpdatedAt,
			&i.AccessTokenEncrypted,
			&i.RefreshTokenEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByProviderAccount = `-- name: ListRepositoriesByProviderAccount :many
SELECT id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at FROM repositories
WHERE provider_account_id = $1
ORDER BY full_name ASC
`

func (q *Queries) ListRepositoriesByProviderAccount(ctx context.Context, providerAccountID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByProviderAccount, providerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderAccountID,
			&i.ProviderRepositoryID,
			&i.FullName,
			&i.RepositoryIdentityHash,
			&i.IsPrivate,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByUser = `-- name: ListRepositoriesByUser :many
SELECT id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at FROM repositories
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRepositoriesByUser(ctx context.Context, userID uuid.UUID) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProviderAccountID,
			&i.ProviderRepositoryID,
			&i.FullName,
			&i.RepositoryIdentityHash,
			&i.IsPrivate,
			&i.DefaultBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderAccountOAuthData = `-- name: UpdateProviderAccountOAuthData :one
UPDATE provider_accounts
SET
    provider_username      = $2,
    provider_email         = $3,
    status                 = $4,
    access_token_encrypted = $5,
    refresh_token_encrypted = $6,
    updated_at             = now()
WHERE id = $1
RETURNING id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted
`

type UpdateProviderAccountOAuthDataParams struct {
	ID                    uuid.UUID             `json:"id"`
	ProviderUsername      string                `json:"provider_username"`
	ProviderEmail         pgtype.Text           `json:"provider_email"`
	Status                ProviderAccountStatus `json:"status"`
	AccessTokenEncrypted  string                `json:"access_token_encrypted"`
	RefreshTokenEncrypted pgtype.Text           `json:"refresh_token_encrypted"`
}

func (q *Queries) UpdateProviderAccountOAuthData(ctx context.Context, arg UpdateProviderAccountOAuthDataParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, updateProviderAccountOAuthData,
		arg.ID,
		arg.ProviderUsername,
		arg.ProviderEmail,
		arg.Status,
		arg.AccessTokenEncrypted,
		arg.RefreshTokenEncrypted,
	)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderAccountID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
	)
	return i, err
}

const updateProviderAccountStatus = `-- name: UpdateProviderAccountStatus :one
UPDATE provider_accounts
SET
    status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, provider_type, provider_account_id, provider_username, provider_email, status, connected_at, updated_at, access_token_encrypted, refresh_token_encrypted
`

type UpdateProviderAccountStatusParams struct {
	ID     uuid.UUID             `json:"id"`
	Status ProviderAccountStatus `json:"status"`
}

func (q *Queries) UpdateProviderAccountStatus(ctx context.Context, arg UpdateProviderAccountStatusParams) (ProviderAccount, error) {
	row := q.db.QueryRow(ctx, updateProviderAccountStatus, arg.ID, arg.Status)
	var i ProviderAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderType,
		&i.ProviderAccountID,
		&i.ProviderUsername,
		&i.ProviderEmail,
		&i.Status,
		&i.ConnectedAt,
		&i.UpdatedAt,
		&i.AccessTokenEncrypted,
		&i.RefreshTokenEncrypted,
	)
	return i, err
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET
    is_private     = COALESCE($2, is_private),
    default_branch = COALESCE($3, default_branch),
    updated_at     = now()
WHERE id = $1
RETURNING id, user_id, provider_account_id, provider_repository_id, full_name, repository_identity_hash, is_private, default_branch, created_at, updated_at
`

type UpdateRepositoryParams struct {
	ID            uuid.UUID   `json:"id"`
	IsPrivate     pgtype.Bool `json:"is_private"`
	DefaultBranch pgtype.Text `json:"default_branch"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository, arg.ID, arg.IsPrivate, arg.DefaultBranch)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProviderAccountID,
		&i.ProviderRepositoryID,
		&i.FullName,
		&i.RepositoryIdentityHash,
		&i.IsPrivate,
		&i.DefaultBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
