// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountFindingsByJobAndSeverity(ctx context.Context, jobID uuid.UUID) ([]CountFindingsByJobAndSeverityRow, error)
	// Count active API keys for a project
	CountProjectAPIKeys(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjectsByUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountScanDependencyResults(ctx context.Context, arg CountScanDependencyResultsParams) (int64, error)
	CountUnifiedProjectScans(ctx context.Context, projectKey string) (int64, error)
	CountUnifiedUserScans(ctx context.Context, arg CountUnifiedUserScansParams) (int64, error)
	CreateAISuggestion(ctx context.Context, arg CreateAISuggestionParams) (AiSuggestion, error)
	// API Key Management Queries
	// Create a new API key for a project
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error)
	CreateFinding(ctx context.Context, arg CreateFindingParams) (Finding, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProviderAccount(ctx context.Context, arg CreateProviderAccountParams) (ProviderAccount, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateRepositorySnapshot(ctx context.Context, arg CreateRepositorySnapshotParams) (RepositorySnapshot, error)
	CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error)
	CreateScanResult(ctx context.Context, arg CreateScanResultParams) (ScanResult, error)
	CreateScanStep(ctx context.Context, arg CreateScanStepParams) (ScanStep, error)
	CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error)
	CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error)
	CreateToolCategory(ctx context.Context, arg CreateToolCategoryParams) (ToolCategory, error)
	CreateUnifiedScan(ctx context.Context, arg CreateUnifiedScanParams) (Scan, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Hard delete an API key (use with caution)
	DeleteAPIKey(ctx context.Context, keyID uuid.UUID) error
	DeleteProject(ctx context.Context, arg DeleteProjectParams) error
	DeleteProjectFindings(ctx context.Context, projectID uuid.UUID) error
	// scan_steps will be auto-deleted via ON DELETE CASCADE from scan_jobs
	DeleteProjectScanJobs(ctx context.Context, projectID uuid.UUID) error
	DeleteProjectScanResults(ctx context.Context, projectID uuid.UUID) error
	DeleteProjectTargets(ctx context.Context, projectID uuid.UUID) error
	DeleteProviderAccount(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, reportID uuid.UUID) error
	DeleteRepository(ctx context.Context, id uuid.UUID) error
	DeleteScanJob(ctx context.Context, jobID uuid.UUID) error
	DeleteTarget(ctx context.Context, arg DeleteTargetParams) error
	DeleteTool(ctx context.Context, toolID uuid.UUID) error
	DeleteToolCategory(ctx context.Context, categoryID uuid.UUID) error
	DeleteUnifiedScan(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteUser(ctx context.Context, userID uuid.UUID) (int64, error)
	FinishScanJob(ctx context.Context, arg FinishScanJobParams) (ScanJob, error)
	FinishScanStep(ctx context.Context, arg FinishScanStepParams) (ScanStep, error)
	GetAISuggestionByJobID(ctx context.Context, jobID uuid.UUID) (AiSuggestion, error)
	// Retrieve API key by its hashed secret (for validation)
	GetAPIKeyByHashedSecret(ctx context.Context, hashedSecret string) (ApiKey, error)
	// Retrieve API key by ID
	GetAPIKeyByID(ctx context.Context, keyID uuid.UUID) (ApiKey, error)
	// Retrieve API key by prefix
	GetAPIKeyByPrefix(ctx context.Context, prefix pgtype.Text) (ApiKey, error)
	// Get active API key by hashed secret (commonly used for validation)
	GetActiveAPIKeyByHashedSecret(ctx context.Context, hashedSecret string) (ApiKey, error)
	GetDocumentByID(ctx context.Context, documentID uuid.UUID) (Document, error)
	GetFindingByID(ctx context.Context, findingID uuid.UUID) (Finding, error)
	GetParsedDataByStep(ctx context.Context, arg GetParsedDataByStepParams) (GetParsedDataByStepRow, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectByIDInternal(ctx context.Context, projectID uuid.UUID) (Project, error)
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error)
	GetProviderAccountByID(ctx context.Context, id uuid.UUID) (ProviderAccount, error)
	GetProviderAccountByIdentity(ctx context.Context, arg GetProviderAccountByIdentityParams) (ProviderAccount, error)
	GetReportByID(ctx context.Context, reportID uuid.UUID) (Report, error)
	GetRepositoryByID(ctx context.Context, id uuid.UUID) (Repository, error)
	GetRepositoryByIdentityHash(ctx context.Context, repositoryIdentityHash string) (Repository, error)
	GetRepositorySnapshotByCommit(ctx context.Context, arg GetRepositorySnapshotByCommitParams) (RepositorySnapshot, error)
	GetRepositorySnapshotByID(ctx context.Context, id uuid.UUID) (RepositorySnapshot, error)
	GetRepositorySnapshotBySourceHash(ctx context.Context, sourceSnapshotHash string) (RepositorySnapshot, error)
	GetScanDependencySummary(ctx context.Context, scanID uuid.UUID) (GetScanDependencySummaryRow, error)
	GetScanDependencySummaryByEcosystem(ctx context.Context, scanID uuid.UUID) ([]GetScanDependencySummaryByEcosystemRow, error)
	GetScanDependencySummaryByLanguage(ctx context.Context, scanID uuid.UUID) ([]GetScanDependencySummaryByLanguageRow, error)
	GetScanJobByID(ctx context.Context, jobID uuid.UUID) (ScanJob, error)
	GetScanResultByID(ctx context.Context, resultID uuid.UUID) (ScanResult, error)
	GetScanSonarResult(ctx context.Context, scanID uuid.UUID) (ScanSonarResult, error)
	GetScanStepByID(ctx context.Context, stepID uuid.UUID) (ScanStep, error)
	GetTargetByID(ctx context.Context, targetID uuid.UUID) (Target, error)
	GetToolByID(ctx context.Context, toolID uuid.UUID) (Tool, error)
	GetToolByName(ctx context.Context, toolName string) (Tool, error)
	GetToolCategoryByID(ctx context.Context, categoryID uuid.UUID) (ToolCategory, error)
	GetToolWithVersion(ctx context.Context, toolID uuid.UUID) (GetToolWithVersionRow, error)
	GetTranslation(ctx context.Context, arg GetTranslationParams) (DocumentTranslation, error)
	GetUnifiedScan(ctx context.Context, id uuid.UUID) (Scan, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	// List all API keys for a project (including revoked)
	ListAPIKeysByProject(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error)
	// List active API keys for a project
	ListActiveAPIKeysByProject(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error)
	ListActiveTools(ctx context.Context) ([]Tool, error)
	ListFindingsByJob(ctx context.Context, jobID uuid.UUID) ([]Finding, error)
	ListFindingsByProject(ctx context.Context, projectID uuid.UUID) ([]Finding, error)
	ListFindingsBySeverity(ctx context.Context, arg ListFindingsBySeverityParams) ([]Finding, error)
	ListProjectsByUser(ctx context.Context, userID uuid.UUID) ([]Project, error)
	ListProviderAccountsByUser(ctx context.Context, userID uuid.UUID) ([]ProviderAccount, error)
	ListReportsByProject(ctx context.Context, projectID uuid.UUID) ([]Report, error)
	ListRepositoriesByProviderAccount(ctx context.Context, providerAccountID uuid.UUID) ([]Repository, error)
	ListRepositoriesByUser(ctx context.Context, userID uuid.UUID) ([]Repository, error)
	ListScanDependencyResults(ctx context.Context, arg ListScanDependencyResultsParams) ([]ScanDependencyResult, error)
	ListScanJobsByProject(ctx context.Context, projectID uuid.UUID) ([]ScanJob, error)
	ListScanJobsByProjectAndStatus(ctx context.Context, arg ListScanJobsByProjectAndStatusParams) ([]ScanJob, error)
	ListScanResultsByJob(ctx context.Context, jobID uuid.UUID) ([]ScanResult, error)
	ListScanResultsBySeverity(ctx context.Context, arg ListScanResultsBySeverityParams) ([]ScanResult, error)
	ListScanResultsByStep(ctx context.Context, arg ListScanResultsByStepParams) ([]ScanResult, error)
	ListScanStepsByJob(ctx context.Context, jobID uuid.UUID) ([]ScanStep, error)
	ListSnapshotsByRepository(ctx context.Context, repositoryID uuid.UUID) ([]RepositorySnapshot, error)
	ListTargetsByProject(ctx context.Context, projectID uuid.UUID) ([]Target, error)
	ListToolCategories(ctx context.Context) ([]ToolCategory, error)
	ListTools(ctx context.Context) ([]Tool, error)
	ListToolsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]Tool, error)
	ListTranslationsByDocument(ctx context.Context, documentID uuid.UUID) ([]DocumentTranslation, error)
	ListUnifiedProjectScans(ctx context.Context, arg ListUnifiedProjectScansParams) ([]Scan, error)
	ListUnifiedUserScans(ctx context.Context, arg ListUnifiedUserScansParams) ([]Scan, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkUnifiedScanFinished(ctx context.Context, id uuid.UUID) (Scan, error)
	MarkUnifiedScanStarted(ctx context.Context, id uuid.UUID) (Scan, error)
	PublishDocument(ctx context.Context, documentID uuid.UUID) (Document, error)
	// Revoke an API key (soft delete)
	RevokeAPIKey(ctx context.Context, keyID uuid.UUID) (ApiKey, error)
	StartScanStep(ctx context.Context, stepID uuid.UUID) (ScanStep, error)
	UpdateAISuggestion(ctx context.Context, arg UpdateAISuggestionParams) (AiSuggestion, error)
	// Update the scopes of an API key
	UpdateAPIKeyScopes(ctx context.Context, arg UpdateAPIKeyScopesParams) (ApiKey, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProviderAccountOAuthData(ctx context.Context, arg UpdateProviderAccountOAuthDataParams) (ProviderAccount, error)
	UpdateProviderAccountStatus(ctx context.Context, arg UpdateProviderAccountStatusParams) (ProviderAccount, error)
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error)
	UpdateRepositorySnapshotDependencyHash(ctx context.Context, arg UpdateRepositorySnapshotDependencyHashParams) (RepositorySnapshot, error)
	UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (ScanJob, error)
	UpdateScanStepStatus(ctx context.Context, arg UpdateScanStepStatusParams) (ScanStep, error)
	UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error)
	UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error)
	UpdateToolCategory(ctx context.Context, arg UpdateToolCategoryParams) (ToolCategory, error)
	UpdateUnifiedScanClonePhase(ctx context.Context, arg UpdateUnifiedScanClonePhaseParams) (Scan, error)
	UpdateUnifiedScanOwaspPhase(ctx context.Context, arg UpdateUnifiedScanOwaspPhaseParams) (Scan, error)
	UpdateUnifiedScanProgress(ctx context.Context, arg UpdateUnifiedScanProgressParams) (Scan, error)
	UpdateUnifiedScanSonarProjectKey(ctx context.Context, arg UpdateUnifiedScanSonarProjectKeyParams) (Scan, error)
	UpdateUnifiedScanSonarqubePhase(ctx context.Context, arg UpdateUnifiedScanSonarqubePhaseParams) (Scan, error)
	UpdateUnifiedScanStatus(ctx context.Context, arg UpdateUnifiedScanStatusParams) (Scan, error)
	UpdateUnifiedScanTrivyPhase(ctx context.Context, arg UpdateUnifiedScanTrivyPhaseParams) (Scan, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertFinding(ctx context.Context, arg UpsertFindingParams) (Finding, error)
	UpsertScanDependencyResult(ctx context.Context, arg UpsertScanDependencyResultParams) (ScanDependencyResult, error)
	UpsertScanSonarResult(ctx context.Context, arg UpsertScanSonarResultParams) (ScanSonarResult, error)
	UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (DocumentTranslation, error)
}

var _ Querier = (*Queries)(nil)
