// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (default_locale, is_publish)
VALUES ($1, $2)
RETURNING document_id, default_locale, is_publish, created_at, last_modified_at
`

type CreateDocumentParams struct {
	DefaultLocale pgtype.Text `json:"default_locale"`
	IsPublish     pgtype.Bool `json:"is_publish"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.DefaultLocale, arg.IsPublish)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.DefaultLocale,
		&i.IsPublish,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (project_id, scope_id, scope_type, document_id, file_name, file_extension)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING report_id, project_id, scope_id, scope_type, document_id, file_name, file_extension, created_at
`

type CreateReportParams struct {
	ProjectID     uuid.UUID       `json:"project_id"`
	ScopeID       uuid.UUID       `json:"scope_id"`
	ScopeType     ReportScopeType `json:"scope_type"`
	DocumentID    pgtype.UUID     `json:"document_id"`
	FileName      pgtype.Text     `json:"file_name"`
	FileExtension pgtype.Text     `json:"file_extension"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ProjectID,
		arg.ScopeID,
		arg.ScopeType,
		arg.DocumentID,
		arg.FileName,
		arg.FileExtension,
	)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ProjectID,
		&i.ScopeID,
		&i.ScopeType,
		&i.DocumentID,
		&i.FileName,
		&i.FileExtension,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE report_id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, reportID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, reportID)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT document_id, default_locale, is_publish, created_at, last_modified_at FROM documents
WHERE document_id = $1
`

func (q *Queries) GetDocumentByID(ctx context.Context, documentID uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.DefaultLocale,
		&i.IsPublish,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT report_id, project_id, scope_id, scope_type, document_id, file_name, file_extension, created_at FROM reports
WHERE report_id = $1
`

func (q *Queries) GetReportByID(ctx context.Context, reportID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, reportID)
	var i Report
	err := row.Scan(
		&i.ReportID,
		&i.ProjectID,
		&i.ScopeID,
		&i.ScopeType,
		&i.DocumentID,
		&i.FileName,
		&i.FileExtension,
		&i.CreatedAt,
	)
	return i, err
}

const getTranslation = `-- name: GetTranslation :one
SELECT translation_id, document_id, locale, title, content, created_at, last_modified_at FROM document_translations
WHERE document_id = $1 AND locale = $2
`

type GetTranslationParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	Locale     string    `json:"locale"`
}

func (q *Queries) GetTranslation(ctx context.Context, arg GetTranslationParams) (DocumentTranslation, error) {
	row := q.db.QueryRow(ctx, getTranslation, arg.DocumentID, arg.Locale)
	var i DocumentTranslation
	err := row.Scan(
		&i.TranslationID,
		&i.DocumentID,
		&i.Locale,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const listReportsByProject = `-- name: ListReportsByProject :many
SELECT report_id, project_id, scope_id, scope_type, document_id, file_name, file_extension, created_at FROM reports
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReportsByProject(ctx context.Context, projectID uuid.UUID) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ReportID,
			&i.ProjectID,
			&i.ScopeID,
			&i.ScopeType,
			&i.DocumentID,
			&i.FileName,
			&i.FileExtension,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslationsByDocument = `-- name: ListTranslationsByDocument :many
SELECT translation_id, document_id, locale, title, content, created_at, last_modified_at FROM document_translations
WHERE document_id = $1
`

func (q *Queries) ListTranslationsByDocument(ctx context.Context, documentID uuid.UUID) ([]DocumentTranslation, error) {
	rows, err := q.db.Query(ctx, listTranslationsByDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentTranslation
	for rows.Next() {
		var i DocumentTranslation
		if err := rows.Scan(
			&i.TranslationID,
			&i.DocumentID,
			&i.Locale,
			&i.Title,
			&i.Content,
			&i.CreatedAt,
			&i.LastModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishDocument = `-- name: PublishDocument :one
UPDATE documents
SET
    is_publish       = true,
    last_modified_at = now()
WHERE document_id = $1
RETURNING document_id, default_locale, is_publish, created_at, last_modified_at
`

func (q *Queries) PublishDocument(ctx context.Context, documentID uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, publishDocument, documentID)
	var i Document
	err := row.Scan(
		&i.DocumentID,
		&i.DefaultLocale,
		&i.IsPublish,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}

const upsertTranslation = `-- name: UpsertTranslation :one
INSERT INTO document_translations (document_id, locale, title, content)
VALUES ($1, $2, $3, $4)
ON CONFLICT (document_id, locale)
DO UPDATE SET
    title            = EXCLUDED.title,
    content          = EXCLUDED.content,
    last_modified_at = now()
RETURNING translation_id, document_id, locale, title, content, created_at, last_modified_at
`

type UpsertTranslationParams struct {
	DocumentID uuid.UUID   `json:"document_id"`
	Locale     string      `json:"locale"`
	Title      pgtype.Text `json:"title"`
	Content    pgtype.Text `json:"content"`
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) (DocumentTranslation, error) {
	row := q.db.QueryRow(ctx, upsertTranslation,
		arg.DocumentID,
		arg.Locale,
		arg.Title,
		arg.Content,
	)
	var i DocumentTranslation
	err := row.Scan(
		&i.TranslationID,
		&i.DocumentID,
		&i.Locale,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.LastModifiedAt,
	)
	return i, err
}
