// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScanJob = `-- name: CreateScanJob :one
INSERT INTO scan_jobs (project_id, target_id, triggered_by, api_key_id, execution_mode)
VALUES ($1, $2, $3, $4, $5)
RETURNING job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration
`

type CreateScanJobParams struct {
	ProjectID     uuid.UUID         `json:"project_id"`
	TargetID      uuid.UUID         `json:"target_id"`
	TriggeredBy   pgtype.UUID       `json:"triggered_by"`
	ApiKeyID      pgtype.UUID       `json:"api_key_id"`
	ExecutionMode NullExecutionMode `json:"execution_mode"`
}

func (q *Queries) CreateScanJob(ctx context.Context, arg CreateScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, createScanJob,
		arg.ProjectID,
		arg.TargetID,
		arg.TriggeredBy,
		arg.ApiKeyID,
		arg.ExecutionMode,
	)
	var i ScanJob
	err := row.Scan(
		&i.JobID,
		&i.ProjectID,
		&i.TargetID,
		&i.TriggeredBy,
		&i.ApiKeyID,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ScanDuration,
	)
	return i, err
}

const deleteScanJob = `-- name: DeleteScanJob :exec
DELETE FROM scan_jobs
WHERE job_id = $1
`

func (q *Queries) DeleteScanJob(ctx context.Context, jobID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteScanJob, jobID)
	return err
}

const finishScanJob = `-- name: FinishScanJob :one
UPDATE scan_jobs
SET
    status      = $2,
    finished_at = now()
WHERE job_id = $1
RETURNING job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration
`

type FinishScanJobParams struct {
	JobID  uuid.UUID         `json:"job_id"`
	Status NullScanJobStatus `json:"status"`
}

func (q *Queries) FinishScanJob(ctx context.Context, arg FinishScanJobParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, finishScanJob, arg.JobID, arg.Status)
	var i ScanJob
	err := row.Scan(
		&i.JobID,
		&i.ProjectID,
		&i.TargetID,
		&i.TriggeredBy,
		&i.ApiKeyID,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ScanDuration,
	)
	return i, err
}

const getScanJobByID = `-- name: GetScanJobByID :one
SELECT job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration FROM scan_jobs
WHERE job_id = $1
`

func (q *Queries) GetScanJobByID(ctx context.Context, jobID uuid.UUID) (ScanJob, error) {
	row := q.db.QueryRow(ctx, getScanJobByID, jobID)
	var i ScanJob
	err := row.Scan(
		&i.JobID,
		&i.ProjectID,
		&i.TargetID,
		&i.TriggeredBy,
		&i.ApiKeyID,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ScanDuration,
	)
	return i, err
}

const listScanJobsByProject = `-- name: ListScanJobsByProject :many
SELECT job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration FROM scan_jobs
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListScanJobsByProject(ctx context.Context, projectID uuid.UUID) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listScanJobsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanJob
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.JobID,
			&i.ProjectID,
			&i.TargetID,
			&i.TriggeredBy,
			&i.ApiKeyID,
			&i.Status,
			&i.ExecutionMode,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ScanDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScanJobsByProjectAndStatus = `-- name: ListScanJobsByProjectAndStatus :many
SELECT job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration FROM scan_jobs
WHERE project_id = $1
  AND status = $2
ORDER BY created_at DESC
`

type ListScanJobsByProjectAndStatusParams struct {
	ProjectID uuid.UUID         `json:"project_id"`
	Status    NullScanJobStatus `json:"status"`
}

func (q *Queries) ListScanJobsByProjectAndStatus(ctx context.Context, arg ListScanJobsByProjectAndStatusParams) ([]ScanJob, error) {
	rows, err := q.db.Query(ctx, listScanJobsByProjectAndStatus, arg.ProjectID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanJob
	for rows.Next() {
		var i ScanJob
		if err := rows.Scan(
			&i.JobID,
			&i.ProjectID,
			&i.TargetID,
			&i.TriggeredBy,
			&i.ApiKeyID,
			&i.Status,
			&i.ExecutionMode,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.ScanDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScanJobStatus = `-- name: UpdateScanJobStatus :one
UPDATE scan_jobs
SET status = $2
WHERE job_id = $1
RETURNING job_id, project_id, target_id, triggered_by, api_key_id, status, execution_mode, created_at, finished_at, scan_duration
`

type UpdateScanJobStatusParams struct {
	JobID  uuid.UUID         `json:"job_id"`
	Status NullScanJobStatus `json:"status"`
}

func (q *Queries) UpdateScanJobStatus(ctx context.Context, arg UpdateScanJobStatusParams) (ScanJob, error) {
	row := q.db.QueryRow(ctx, updateScanJobStatus, arg.JobID, arg.Status)
	var i ScanJob
	err := row.Scan(
		&i.JobID,
		&i.ProjectID,
		&i.TargetID,
		&i.TriggeredBy,
		&i.ApiKeyID,
		&i.Status,
		&i.ExecutionMode,
		&i.CreatedAt,
		&i.FinishedAt,
		&i.ScanDuration,
	)
	return i, err
}
