// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scan_steps.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScanStep = `-- name: CreateScanStep :one
INSERT INTO scan_steps (job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at
`

type CreateScanStepParams struct {
	JobID       uuid.UUID       `json:"job_id"`
	ToolID      uuid.UUID       `json:"tool_id"`
	ToolVersion pgtype.Text     `json:"tool_version"`
	InputSource InputSourceType `json:"input_source"`
	InputStepID pgtype.UUID     `json:"input_step_id"`
	StepKey     string          `json:"step_key"`
	StepOrder   int32           `json:"step_order"`
}

func (q *Queries) CreateScanStep(ctx context.Context, arg CreateScanStepParams) (ScanStep, error) {
	row := q.db.QueryRow(ctx, createScanStep,
		arg.JobID,
		arg.ToolID,
		arg.ToolVersion,
		arg.InputSource,
		arg.InputStepID,
		arg.StepKey,
		arg.StepOrder,
	)
	var i ScanStep
	err := row.Scan(
		&i.StepID,
		&i.JobID,
		&i.ToolID,
		&i.ToolVersion,
		&i.InputSource,
		&i.InputStepID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const finishScanStep = `-- name: FinishScanStep :one
UPDATE scan_steps
SET
    status      = $2,
    finished_at = now()
WHERE step_id = $1
RETURNING step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at
`

type FinishScanStepParams struct {
	StepID uuid.UUID          `json:"step_id"`
	Status NullScanStepStatus `json:"status"`
}

func (q *Queries) FinishScanStep(ctx context.Context, arg FinishScanStepParams) (ScanStep, error) {
	row := q.db.QueryRow(ctx, finishScanStep, arg.StepID, arg.Status)
	var i ScanStep
	err := row.Scan(
		&i.StepID,
		&i.JobID,
		&i.ToolID,
		&i.ToolVersion,
		&i.InputSource,
		&i.InputStepID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getScanStepByID = `-- name: GetScanStepByID :one
SELECT step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at FROM scan_steps
WHERE step_id = $1
`

func (q *Queries) GetScanStepByID(ctx context.Context, stepID uuid.UUID) (ScanStep, error) {
	row := q.db.QueryRow(ctx, getScanStepByID, stepID)
	var i ScanStep
	err := row.Scan(
		&i.StepID,
		&i.JobID,
		&i.ToolID,
		&i.ToolVersion,
		&i.InputSource,
		&i.InputStepID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listScanStepsByJob = `-- name: ListScanStepsByJob :many
SELECT step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at FROM scan_steps
WHERE job_id = $1
ORDER BY step_order ASC
`

func (q *Queries) ListScanStepsByJob(ctx context.Context, jobID uuid.UUID) ([]ScanStep, error) {
	rows, err := q.db.Query(ctx, listScanStepsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScanStep
	for rows.Next() {
		var i ScanStep
		if err := rows.Scan(
			&i.StepID,
			&i.JobID,
			&i.ToolID,
			&i.ToolVersion,
			&i.InputSource,
			&i.InputStepID,
			&i.StepKey,
			&i.StepOrder,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startScanStep = `-- name: StartScanStep :one
UPDATE scan_steps
SET
    status     = 'running',
    started_at = now()
WHERE step_id = $1
RETURNING step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at
`

func (q *Queries) StartScanStep(ctx context.Context, stepID uuid.UUID) (ScanStep, error) {
	row := q.db.QueryRow(ctx, startScanStep, stepID)
	var i ScanStep
	err := row.Scan(
		&i.StepID,
		&i.JobID,
		&i.ToolID,
		&i.ToolVersion,
		&i.InputSource,
		&i.InputStepID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateScanStepStatus = `-- name: UpdateScanStepStatus :one
UPDATE scan_steps
SET status = $2
WHERE step_id = $1
RETURNING step_id, job_id, tool_id, tool_version, input_source, input_step_id, step_key, step_order, status, started_at, finished_at, created_at
`

type UpdateScanStepStatusParams struct {
	StepID uuid.UUID          `json:"step_id"`
	Status NullScanStepStatus `json:"status"`
}

func (q *Queries) UpdateScanStepStatus(ctx context.Context, arg UpdateScanStepStatusParams) (ScanStep, error) {
	row := q.db.QueryRow(ctx, updateScanStepStatus, arg.StepID, arg.Status)
	var i ScanStep
	err := row.Scan(
		&i.StepID,
		&i.JobID,
		&i.ToolID,
		&i.ToolVersion,
		&i.InputSource,
		&i.InputStepID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}
