// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: targets.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTarget = `-- name: CreateTarget :one
INSERT INTO targets (project_id, name, type, description)
VALUES ($1, $2, $3, $4)
RETURNING target_id, project_id, name, type, description, created_at
`

type CreateTargetParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateTarget(ctx context.Context, arg CreateTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, createTarget,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.Description,
	)
	var i Target
	err := row.Scan(
		&i.TargetID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTarget = `-- name: DeleteTarget :exec
DELETE FROM targets
WHERE target_id = $1 AND project_id = $2
`

type DeleteTargetParams struct {
	TargetID  uuid.UUID `json:"target_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

func (q *Queries) DeleteTarget(ctx context.Context, arg DeleteTargetParams) error {
	_, err := q.db.Exec(ctx, deleteTarget, arg.TargetID, arg.ProjectID)
	return err
}

const getTargetByID = `-- name: GetTargetByID :one
SELECT target_id, project_id, name, type, description, created_at FROM targets
WHERE target_id = $1
`

func (q *Queries) GetTargetByID(ctx context.Context, targetID uuid.UUID) (Target, error) {
	row := q.db.QueryRow(ctx, getTargetByID, targetID)
	var i Target
	err := row.Scan(
		&i.TargetID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listTargetsByProject = `-- name: ListTargetsByProject :many
SELECT target_id, project_id, name, type, description, created_at FROM targets
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTargetsByProject(ctx context.Context, projectID uuid.UUID) ([]Target, error) {
	rows, err := q.db.Query(ctx, listTargetsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Target
	for rows.Next() {
		var i Target
		if err := rows.Scan(
			&i.TargetID,
			&i.ProjectID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTarget = `-- name: UpdateTarget :one
UPDATE targets
SET
    name        = COALESCE($3, name),
    type        = COALESCE($4, type),
    description = COALESCE($5, description)
WHERE target_id = $1 AND project_id = $2
RETURNING target_id, project_id, name, type, description, created_at
`

type UpdateTargetParams struct {
	TargetID    uuid.UUID   `json:"target_id"`
	ProjectID   uuid.UUID   `json:"project_id"`
	Name        pgtype.Text `json:"name"`
	Type        pgtype.Text `json:"type"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTarget(ctx context.Context, arg UpdateTargetParams) (Target, error) {
	row := q.db.QueryRow(ctx, updateTarget,
		arg.TargetID,
		arg.ProjectID,
		arg.Name,
		arg.Type,
		arg.Description,
	)
	var i Target
	err := row.Scan(
		&i.TargetID,
		&i.ProjectID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
