// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tools.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTool = `-- name: CreateTool :one
INSERT INTO tools (
    category_id, tool_name, tool_description, tool_long_description,
    examples, input_schema, output_schema, scan_config,
    install_method, version_id, image_ref, image_source, denied_options,
    shadow_output_config, parser_config
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15
)
RETURNING tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config
`

type CreateToolParams struct {
	CategoryID          pgtype.UUID     `json:"category_id"`
	ToolName            string          `json:"tool_name"`
	ToolDescription     pgtype.Text     `json:"tool_description"`
	ToolLongDescription pgtype.Text     `json:"tool_long_description"`
	Examples            json.RawMessage `json:"examples"`
	InputSchema         []byte          `json:"input_schema"`
	OutputSchema        []byte          `json:"output_schema"`
	ScanConfig          []byte          `json:"scan_config"`
	InstallMethod       pgtype.Text     `json:"install_method"`
	VersionID           uuid.UUID       `json:"version_id"`
	ImageRef            pgtype.Text     `json:"image_ref"`
	ImageSource         pgtype.Text     `json:"image_source"`
	DeniedOptions       []string        `json:"denied_options"`
	ShadowOutputConfig  []byte          `json:"shadow_output_config"`
	ParserConfig        []byte          `json:"parser_config"`
}

func (q *Queries) CreateTool(ctx context.Context, arg CreateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, createTool,
		arg.CategoryID,
		arg.ToolName,
		arg.ToolDescription,
		arg.ToolLongDescription,
		arg.Examples,
		arg.InputSchema,
		arg.OutputSchema,
		arg.ScanConfig,
		arg.InstallMethod,
		arg.VersionID,
		arg.ImageRef,
		arg.ImageSource,
		arg.DeniedOptions,
		arg.ShadowOutputConfig,
		arg.ParserConfig,
	)
	var i Tool
	err := row.Scan(
		&i.ToolID,
		&i.CategoryID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolLongDescription,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ScanConfig,
		&i.InstallMethod,
		&i.ImageRef,
		&i.ImageSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.DeniedOptions,
		&i.Examples,
		&i.ShadowOutputConfig,
		&i.ParserConfig,
	)
	return i, err
}

const createToolCategory = `-- name: CreateToolCategory :one
INSERT INTO tool_categories (name, description)
VALUES ($1, $2)
RETURNING category_id, name, description, created_at, last_modified
`

type CreateToolCategoryParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateToolCategory(ctx context.Context, arg CreateToolCategoryParams) (ToolCategory, error) {
	row := q.db.QueryRow(ctx, createToolCategory, arg.Name, arg.Description)
	var i ToolCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const deleteTool = `-- name: DeleteTool :exec
DELETE FROM tools
WHERE tool_id = $1
`

func (q *Queries) DeleteTool(ctx context.Context, toolID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTool, toolID)
	return err
}

const deleteToolCategory = `-- name: DeleteToolCategory :exec
DELETE FROM tool_categories
WHERE category_id = $1
`

func (q *Queries) DeleteToolCategory(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteToolCategory, categoryID)
	return err
}

const getToolByID = `-- name: GetToolByID :one
SELECT tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config FROM tools
WHERE tool_id = $1
`

func (q *Queries) GetToolByID(ctx context.Context, toolID uuid.UUID) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByID, toolID)
	var i Tool
	err := row.Scan(
		&i.ToolID,
		&i.CategoryID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolLongDescription,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ScanConfig,
		&i.InstallMethod,
		&i.ImageRef,
		&i.ImageSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.DeniedOptions,
		&i.Examples,
		&i.ShadowOutputConfig,
		&i.ParserConfig,
	)
	return i, err
}

const getToolByName = `-- name: GetToolByName :one
SELECT tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config FROM tools
WHERE tool_name = $1
`

func (q *Queries) GetToolByName(ctx context.Context, toolName string) (Tool, error) {
	row := q.db.QueryRow(ctx, getToolByName, toolName)
	var i Tool
	err := row.Scan(
		&i.ToolID,
		&i.CategoryID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolLongDescription,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ScanConfig,
		&i.InstallMethod,
		&i.ImageRef,
		&i.ImageSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.DeniedOptions,
		&i.Examples,
		&i.ShadowOutputConfig,
		&i.ParserConfig,
	)
	return i, err
}

const getToolCategoryByID = `-- name: GetToolCategoryByID :one
SELECT category_id, name, description, created_at, last_modified FROM tool_categories
WHERE category_id = $1
`

func (q *Queries) GetToolCategoryByID(ctx context.Context, categoryID uuid.UUID) (ToolCategory, error) {
	row := q.db.QueryRow(ctx, getToolCategoryByID, categoryID)
	var i ToolCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const getToolWithVersion = `-- name: GetToolWithVersion :one
SELECT 
    t.tool_id, t.category_id, t.tool_name, t.tool_description, t.tool_long_description, t.input_schema, t.output_schema, t.scan_config, t.install_method, t.image_ref, t.image_source, t.is_active, t.created_at, t.updated_at, t.version_id, t.denied_options, t.examples, t.shadow_output_config, t.parser_config, 
    v.version_number, 
    v.installed_at 
FROM tools t
JOIN versions v ON t.version_id = v.version_id
WHERE t.tool_id = $1
`

type GetToolWithVersionRow struct {
	ToolID              uuid.UUID          `json:"tool_id"`
	CategoryID          pgtype.UUID        `json:"category_id"`
	ToolName            string             `json:"tool_name"`
	ToolDescription     pgtype.Text        `json:"tool_description"`
	ToolLongDescription pgtype.Text        `json:"tool_long_description"`
	InputSchema         []byte             `json:"input_schema"`
	OutputSchema        []byte             `json:"output_schema"`
	ScanConfig          []byte             `json:"scan_config"`
	InstallMethod       pgtype.Text        `json:"install_method"`
	ImageRef            pgtype.Text        `json:"image_ref"`
	ImageSource         pgtype.Text        `json:"image_source"`
	IsActive            pgtype.Bool        `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	VersionID           uuid.UUID          `json:"version_id"`
	DeniedOptions       []string           `json:"denied_options"`
	Examples            json.RawMessage    `json:"examples"`
	ShadowOutputConfig  []byte             `json:"shadow_output_config"`
	ParserConfig        []byte             `json:"parser_config"`
	VersionNumber       string             `json:"version_number"`
	InstalledAt         pgtype.Timestamptz `json:"installed_at"`
}

func (q *Queries) GetToolWithVersion(ctx context.Context, toolID uuid.UUID) (GetToolWithVersionRow, error) {
	row := q.db.QueryRow(ctx, getToolWithVersion, toolID)
	var i GetToolWithVersionRow
	err := row.Scan(
		&i.ToolID,
		&i.CategoryID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolLongDescription,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ScanConfig,
		&i.InstallMethod,
		&i.ImageRef,
		&i.ImageSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.DeniedOptions,
		&i.Examples,
		&i.ShadowOutputConfig,
		&i.ParserConfig,
		&i.VersionNumber,
		&i.InstalledAt,
	)
	return i, err
}

const listActiveTools = `-- name: ListActiveTools :many
SELECT tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config FROM tools
WHERE is_active = true
ORDER BY tool_name ASC
`

func (q *Queries) ListActiveTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listActiveTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ToolID,
			&i.CategoryID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolLongDescription,
			&i.InputSchema,
			&i.OutputSchema,
			&i.ScanConfig,
			&i.InstallMethod,
			&i.ImageRef,
			&i.ImageSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionID,
			&i.DeniedOptions,
			&i.Examples,
			&i.ShadowOutputConfig,
			&i.ParserConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCategories = `-- name: ListToolCategories :many
SELECT category_id, name, description, created_at, last_modified FROM tool_categories
ORDER BY name ASC
`

func (q *Queries) ListToolCategories(ctx context.Context) ([]ToolCategory, error) {
	rows, err := q.db.Query(ctx, listToolCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolCategory
	for rows.Next() {
		var i ToolCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTools = `-- name: ListTools :many
SELECT tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config FROM tools
ORDER BY tool_name ASC
`

func (q *Queries) ListTools(ctx context.Context) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listTools)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ToolID,
			&i.CategoryID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolLongDescription,
			&i.InputSchema,
			&i.OutputSchema,
			&i.ScanConfig,
			&i.InstallMethod,
			&i.ImageRef,
			&i.ImageSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionID,
			&i.DeniedOptions,
			&i.Examples,
			&i.ShadowOutputConfig,
			&i.ParserConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolsByCategory = `-- name: ListToolsByCategory :many
SELECT tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config FROM tools
WHERE category_id = $1
ORDER BY tool_name ASC
`

func (q *Queries) ListToolsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]Tool, error) {
	rows, err := q.db.Query(ctx, listToolsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tool
	for rows.Next() {
		var i Tool
		if err := rows.Scan(
			&i.ToolID,
			&i.CategoryID,
			&i.ToolName,
			&i.ToolDescription,
			&i.ToolLongDescription,
			&i.InputSchema,
			&i.OutputSchema,
			&i.ScanConfig,
			&i.InstallMethod,
			&i.ImageRef,
			&i.ImageSource,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VersionID,
			&i.DeniedOptions,
			&i.Examples,
			&i.ShadowOutputConfig,
			&i.ParserConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTool = `-- name: UpdateTool :one
UPDATE tools
SET
    category_id           = COALESCE($2, category_id),
    tool_name             = COALESCE($3, tool_name),
    tool_description      = COALESCE($4, tool_description),
    tool_long_description = COALESCE($5, tool_long_description),
    examples              = COALESCE($6, examples),
    input_schema          = COALESCE($7, input_schema),
    output_schema         = COALESCE($8, output_schema),
    scan_config           = COALESCE($9, scan_config),
    install_method        = COALESCE($10, install_method),
    version_id            = COALESCE($11, version_id),
    image_ref             = COALESCE($12, image_ref),
    image_source          = COALESCE($13, image_source),
    denied_options        = COALESCE($14, denied_options),
    shadow_output_config  = COALESCE($15, shadow_output_config),
    parser_config         = COALESCE($16, parser_config),
    is_active             = COALESCE($17, is_active),
    updated_at            = now()
WHERE tool_id = $1
RETURNING tool_id, category_id, tool_name, tool_description, tool_long_description, input_schema, output_schema, scan_config, install_method, image_ref, image_source, is_active, created_at, updated_at, version_id, denied_options, examples, shadow_output_config, parser_config
`

type UpdateToolParams struct {
	ToolID              uuid.UUID   `json:"tool_id"`
	CategoryID          pgtype.UUID `json:"category_id"`
	ToolName            pgtype.Text `json:"tool_name"`
	ToolDescription     pgtype.Text `json:"tool_description"`
	ToolLongDescription pgtype.Text `json:"tool_long_description"`
	Examples            []byte      `json:"examples"`
	InputSchema         []byte      `json:"input_schema"`
	OutputSchema        []byte      `json:"output_schema"`
	ScanConfig          []byte      `json:"scan_config"`
	InstallMethod       pgtype.Text `json:"install_method"`
	VersionID           pgtype.UUID `json:"version_id"`
	ImageRef            pgtype.Text `json:"image_ref"`
	ImageSource         pgtype.Text `json:"image_source"`
	DeniedOptions       []string    `json:"denied_options"`
	ShadowOutputConfig  []byte      `json:"shadow_output_config"`
	ParserConfig        []byte      `json:"parser_config"`
	IsActive            pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateTool(ctx context.Context, arg UpdateToolParams) (Tool, error) {
	row := q.db.QueryRow(ctx, updateTool,
		arg.ToolID,
		arg.CategoryID,
		arg.ToolName,
		arg.ToolDescription,
		arg.ToolLongDescription,
		arg.Examples,
		arg.InputSchema,
		arg.OutputSchema,
		arg.ScanConfig,
		arg.InstallMethod,
		arg.VersionID,
		arg.ImageRef,
		arg.ImageSource,
		arg.DeniedOptions,
		arg.ShadowOutputConfig,
		arg.ParserConfig,
		arg.IsActive,
	)
	var i Tool
	err := row.Scan(
		&i.ToolID,
		&i.CategoryID,
		&i.ToolName,
		&i.ToolDescription,
		&i.ToolLongDescription,
		&i.InputSchema,
		&i.OutputSchema,
		&i.ScanConfig,
		&i.InstallMethod,
		&i.ImageRef,
		&i.ImageSource,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VersionID,
		&i.DeniedOptions,
		&i.Examples,
		&i.ShadowOutputConfig,
		&i.ParserConfig,
	)
	return i, err
}

const updateToolCategory = `-- name: UpdateToolCategory :one
UPDATE tool_categories
SET
    name          = COALESCE($2, name),
    description   = COALESCE($3, description),
    last_modified = now()
WHERE category_id = $1
RETURNING category_id, name, description, created_at, last_modified
`

type UpdateToolCategoryParams struct {
	CategoryID  uuid.UUID   `json:"category_id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateToolCategory(ctx context.Context, arg UpdateToolCategoryParams) (ToolCategory, error) {
	row := q.db.QueryRow(ctx, updateToolCategory, arg.CategoryID, arg.Name, arg.Description)
	var i ToolCategory
	err := row.Scan(
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}
