// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (user_id, username, email, alias_name, avatar_profile)
VALUES ($1, $2, $3, $4, $5)
RETURNING user_id, username, email, alias_name, avatar_profile, created_at, last_modified
`

type CreateUserParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Username      string      `json:"username"`
	Email         string      `json:"email"`
	AliasName     pgtype.Text `json:"alias_name"`
	AvatarProfile pgtype.Text `json:"avatar_profile"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.AliasName,
		arg.AvatarProfile,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.AliasName,
		&i.AvatarProfile,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT user_id, username, email, alias_name, avatar_profile, created_at, last_modified FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.AliasName,
		&i.AvatarProfile,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, username, email, alias_name, avatar_profile, created_at, last_modified FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.AliasName,
		&i.AvatarProfile,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, username, email, alias_name, avatar_profile, created_at, last_modified FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.AliasName,
		&i.AvatarProfile,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT user_id, username, email, alias_name, avatar_profile, created_at, last_modified FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.AliasName,
			&i.AvatarProfile,
			&i.CreatedAt,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    username = COALESCE($2, username),
    email = COALESCE($3, email),
    alias_name    = COALESCE($4, alias_name),
    avatar_profile = COALESCE($5, avatar_profile),
    last_modified = now()
WHERE user_id = $1
RETURNING user_id, username, email, alias_name, avatar_profile, created_at, last_modified
`

type UpdateUserParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	Username      pgtype.Text `json:"username"`
	Email         pgtype.Text `json:"email"`
	AliasName     pgtype.Text `json:"alias_name"`
	AvatarProfile pgtype.Text `json:"avatar_profile"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.UserID,
		arg.Username,
		arg.Email,
		arg.AliasName,
		arg.AvatarProfile,
	)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Email,
		&i.AliasName,
		&i.AvatarProfile,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}
